In [1]:
import os
from pathlib import Path

import numpy as np
import pandas as pd

from dotenv import load_dotenv

load_dotenv()

CF_OUTPUTS = Path(os.getenv("CF_OUTPUTS"))
print(CF_OUTPUTS)
print(CF_OUTPUTS.is_dir())

/home/dyretna/Dokument/Code/GitHub/nightingale_projects/cf_bench/cf_outputs
True

In [2]:
GEN_1_RANDOM = CF_OUTPUTS / "gen1_models_explainers_constraints" / "random_search_exp"
GEN_1_RANDOM.is_dir()

True

In [3]:
batch_data = GEN_1_RANDOM / "XGB_highthres_2026-04-17" / "annotated.csv"
batch_df = pd.read_csv(batch_data)

### set PD options

In [4]:
pd.set_option("display.max_rows", None)

In [5]:
# dtypes
int_columns = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "dosprt", "hltprhc", "Nchanged"]
float_columns = ["bmi", "gower_distance", "risk_before", "predicted_risk_after", "cf_gen_time_sec"]


# Convert and fill NaN with empty strings
batch_df[int_columns] = batch_df[int_columns].astype("Int64").astype("string").fillna("")
batch_df[float_columns] = batch_df[float_columns].round(4).astype("string").fillna("")
batch_df["valid"] = batch_df["valid"].astype("string").fillna("")

In [6]:
batch_df = batch_df.drop(columns=["hltprhc", "target_risk"])
batch_df["cf_id"] = batch_df["cf_id"].replace({"original": "xin"})

In [7]:
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,41.13,,,,0.026,
1,0,cf_1,,,5,5,,,,,,0.0813,2,False,0.026,0.0267
2,0,cf_2,,,6,,4,,,,,0.2,2,False,0.026,0.0278
3,0,cf_3,,,,6,,,21.1844,,,0.0946,2,False,0.026,0.0631
4,0,cf_4,,,1,,,,26.9487,,,0.1664,2,False,0.026,0.0449
5,0,cf_5,,7,,,3,,,,,0.1625,2,False,0.026,0.0243
6,0,cf_6,,,,,,1,21.8062,,,0.1662,2,False,0.026,0.0198
7,0,cf_7,7,,6,,,,,,,0.2,2,True,0.026,0.0016
8,0,cf_8,6,2,,,,,,,,0.1083,2,True,0.026,0.0088
9,0,cf_9,,,,2,,,,,,0.0625,1,True,0.026,0.0099
10,0,cf_10,,,,,,,18.3958,,,0.0086,1,False,0.026,0.0183
11,1,xin,3,4,1,2,3,0,22.3757,0,0.16,,,,0.2497,
12,1,cf_1,,,,,,,20.3772,,,0.0184,1,True,0.2497,0.0664
13,1,cf_2,,7,,,,,,4,,0.2083,2,True,0.2497,0.0465
14,1,cf_3,,,,,,,26.4259,,,0.0373,1,True,0.2497,0.1114
15,1,cf_4,,,,4,,,,,,0.0417,1,True,0.2497,0.0782
16,1,cf_5,,,5,,,,33.9668,,,0.2316,2,False,0.2497,0.1462
17,1,cf_6,,,,,,,29.7997,,,0.0683,1,True,0.2497,0.0424
18,1,cf_7,,,,1,,,,3,,0.0833,2,True,0.2497,0.102
19,1,cf_8,,,,,,,30.8159,6,,0.2026,2,True,0.2497,0.0515
20,1,cf_9,,,,,,,24.2744,3,,0.08,2,True,0.2497,0.0572
21,1,cf_10,,,2,7,,,,,,0.1354,2,False,0.2497,0.1971
22,2,xin,5,3,1,1,4,0,22.694,7,0.16,,,,0.218,
23,2,cf_1,,6,,,,,33.1555,,,0.1596,2,False,0.218,0.1144
24,2,cf_2,,7,,2,,,,,,0.25,2,False,0.218,0.2054
25,2,cf_3,,,,,,,30.5095,,,0.0492,1,True,0.218,0.0154
26,2,cf_4,,,,,,,36.1272,,,0.0845,1,True,0.218,0.006
27,2,cf_5,1,,,,2,,,,,0.25,2,True,0.218,0.0662
28,2,cf_6,,,,,,,16.2674,,,0.0405,1,True,0.218,0.0108
29,2,cf_7,,,,,,,16.7005,4,,0.1627,2,True,0.218,0.0019
30,2,cf_8,,,,,,,25.8549,,,0.0199,1,False,0.218,0.1202
31,2,cf_9,,,,,2,,18.1632,,,0.1535,2,False,0.218,0.236
32,2,cf_10,,,,,,,28.5787,,,0.037,1,True,0.218,0.0271
33,3,xin,3,3,6,6,2,0,24.3418,1,48.81,,,,0.0653,
34,3,cf_1,,,1,5,,,,,,0.15,2,False,0.0653,0.0679
35,3,cf_2,7,,,,,,33.449,,,0.183,2,True,0.0653,0.0175
36,3,cf_3,,,2,,,,31.6046,,,0.1463,2,False,0.0653,0.0655
37,3,cf_4,,1,,,,,,,,0.0625,1,True,0.0653,0.0042
38,3,cf_5,,,,,,,18.7743,,,0.0355,1,False,0.0653,0.0663
39,3,cf_6,,5,,,,,20.3496,,,0.0879,2,False,0.0653,0.0836
40,3,cf_7,,,,,,1,37.9171,,,0.2115,2,True,0.0653,0.0089
41,3,cf_8,,,,1,,,38.3906,,,0.2145,2,False,0.0653,0.1012
42,3,cf_9,,,,,,,24.5613,,,0.0014,1,False,0.0653,0.0903
43,3,cf_10,,2,,,1,,,,,0.1562,2,False,0.0653,0.0442
44,4,xin,5,4,2,7,1,0,21.2585,3,42.86,,,,0.0811,
45,4,cf_1,,,,3,,,,5,,0.2083,2,True,0.0811,0.0386
46,4,cf_2,,,,,,,32.783,,,0.0917,1,False,0.0811,0.1668
47,4,cf_3,,,,,,,24.0237,,,0.022,1,True,0.0811,0.0253
48,4,cf_4,,,,,3,,17.6276,,,0.1539,2,True,0.0811,0.0196
49,4,cf_5,,,,,,,22.2222,,,0.0077,1,True,0.0811,0.0162
50,4,cf_6,,,1,,,,17.0682,,,0.0646,2,True,0.0811,0.0001
51,4,cf_7,,,,,,,25.4325,,,0.0332,1,False,0.0811,0.0503
52,4,cf_8,6,6,,,,,,,,0.25,2,True,0.0811,0.0067
53,4,cf_9,,5,,,,,29.4709,,,0.1278,2,False,0.0811,0.0418
54,4,cf_10,,,5,1,,,,,,0.2188,2,True,0.0811,0.0072
55,5,xin,2,2,1,2,4,0,27.9904,0,0.16,,,,0.0484,
56,5,cf_1,,,,5,,,,4,,0.2083,2,False,0.0484,0.0526
57,5,cf_2,,,2,5,,,,,,0.25,2,False,0.0484,0.0858
58,5,cf_3,,,,,,1,19.8645,,,0.1793,2,True,0.0484,0.0223
59,5,cf_4,,1,,,2,,,,,0.25,2,False,0.0484,0.2196
60,5,cf_5,,,,,,,35.4394,,,0.0498,1,True,0.0484,0.0186
61,5,cf_6,,,,,,,26.8538,,,0.0076,1,False,0.0484,0.0311
62,5,cf_7,3,,,,,,,6,,0.1875,2,True,0.0484,0.0137
63,5,cf_8,,,,,,,21.1682,,,0.0456,1,False,0.0484,0.1099
64,5,cf_9,,,2,,,,,,,0.125,1,False,0.0484,0.1875
65,5,cf_10,4,,,,,,16.7233,,,0.2002,2,True,0.0484,0.0227
66,6,xin,2,3,5,4,1,0,27.6817,4,0.18,,,,0.0539,
67,6,cf_1,,,,,,,35.0214,,,0.0567,1,False,0.0539,0.0624
68,6,cf_2,,,,,,,31.4162,,,0.0288,1,False,0.0539,0.249
69,6,cf_3,,7,6,,,,,,,0.25,2,True,0.0539,0.0047
70,6,cf_4,5,,,,,,30.6169,,,0.1477,2,True,0.0539,0.0155
71,6,cf_5,,4,,,,,32.2127,,,0.0662,2,True,0.0539,0.0191
72,6,cf_6,,5,,,,,18.8318,,,0.1308,2,True,0.0539,0.0038
73,6,cf_7,,,,7,,1,,,,0.25,2,False,0.0539,0.0373
74,6,cf_8,3,,,,,1,,,,0.1667,2,False,0.0539,0.0544
75,6,cf_9,,,,6,,1,,,,0.2083,2,True,0.0539,0.0226
76,6,cf_10,,,6,7,,,,,,0.25,2,False,0.0539,0.0358
77,7,xin,2,3,6,3,1,0,20.4382,2,0.23,,,,0.0565,
78,7,cf_1,6,,,4,,,,,,0.1458,2,False,0.0565,0.0308
79,7,cf_2,7,,1,,,,,,,0.2292,2,True,0.0565,0.005
80,7,cf_3,1,,,,,,16.0572,,,0.0478,2,True,0.0565,0.0026
81,7,cf_4,,,,2,,,17.4349,,,0.081,2,True,0.0565,0.0012
82,7,cf_5,,,,4,,,,6,,0.1875,2,False,0.0565,0.1448
83,7,cf_6,3,,,,4,,,,,0.1458,2,True,0.0565,0.0029
84,7,cf_7,,1,,,,,27.7095,,,0.1697,2,False,0.0565,0.0301
85,7,cf_8,,,,,,,36.3846,,,0.0981,1,False,0.0565,0.1658
86,7,cf_9,5,,2,,,,,,,0.1625,2,True,0.0565,0.0047
87,7,cf_10,3,1,,,,,,,,0.1458,2,True,0.0565,0.0039
88,8,xin,6,4,1,1,1,0,26.0146,0,0.16,,,,0.1216,
89,8,cf_1,4,,,,,,,,,0.125,1,False,0.1216,0.0959
90,8,cf_2,,,,,,1,,3,,0.2,2,True,0.1216,0.0094
91,8,cf_3,,,,,,,32.9573,,,0.0397,1,True,0.1216,0.0369
92,8,cf_4,,,,,,1,19.1466,,,0.1643,2,True,0.1216,0.0031
93,8,cf_5,,2,,5,,,,,,0.1625,2,True,0.1216,0.0066
94,8,cf_6,,5,,,,,38.0565,,,0.1002,2,False,0.1216,0.1703
95,8,cf_7,,,,,2,,,5,,0.25,2,False,0.1216,0.1827
96,8,cf_8,,,,,,,16.2139,,,0.0561,1,True,0.1216,0.0034
97,8,cf_9,,,,6,,1,,,,0.25,2,False,0.1216,0.1344
98,8,cf_10,,6,,,,,,3,,0.1375,2,True,0.1216,0.0092

In [8]:
from cf_bench.utils import select_one_cf_per_query

# Select one CF per observation
# prefers valid CFs without violations, and lowest Gower
single_cf_df = select_one_cf_per_query(batch_df)
single_cf_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,41.13,,,,0.026,
9,0,cf_9,,,,2,,,,,,0.0625,1,True,0.026,0.0099
1,1,xin,3,4,1,2,3,0,22.3757,0,0.16,,,,0.2497,
10,1,cf_1,,,,,,,20.3772,,,0.0184,1,True,0.2497,0.0664
2,2,xin,5,3,1,1,4,0,22.694,7,0.16,,,,0.218,
11,2,cf_10,,,,,,,28.5787,,,0.037,1,True,0.218,0.0271
3,3,xin,3,3,6,6,2,0,24.3418,1,48.81,,,,0.0653,
12,3,cf_4,,1,,,,,,,,0.0625,1,True,0.0653,0.0042
4,4,xin,5,4,2,7,1,0,21.2585,3,42.86,,,,0.0811,
13,4,cf_5,,,,,,,22.2222,,,0.0077,1,True,0.0811,0.0162
5,5,xin,2,2,1,2,4,0,27.9904,0,0.16,,,,0.0484,
14,5,cf_5,,,,,,,35.4394,,,0.0498,1,True,0.0484,0.0186
6,6,xin,2,3,5,4,1,0,27.6817,4,0.18,,,,0.0539,
15,6,cf_5,,4,,,,,32.2127,,,0.0662,2,True,0.0539,0.0191
7,7,xin,2,3,6,3,1,0,20.4382,2,0.23,,,,0.0565,
16,7,cf_3,1,,,,,,16.0572,,,0.0478,2,True,0.0565,0.0026
8,8,xin,6,4,1,1,1,0,26.0146,0,0.16,,,,0.1216,
17,8,cf_3,,,,,,,32.9573,,,0.0397,1,True,0.1216,0.0369