In [1]:
import os
from pathlib import Path

import numpy as np
import pandas as pd

from dotenv import load_dotenv

load_dotenv()

CF_OUTPUTS = Path(os.getenv("CF_OUTPUTS"))
print(CF_OUTPUTS)
print(CF_OUTPUTS.is_dir())

/home/dyretna/Dokument/Code/GitHub/nightingale_projects/cf_bench/cf_outputs
True

In [2]:
GEN_1_RANDOM = CF_OUTPUTS / "gen1_models_explainers_constraints" / "random_search_exp"
GEN_1_RANDOM.is_dir()

True

In [3]:
batch_data = GEN_1_RANDOM / "RF_prange_highthres_2026-04-29" / "annotated.csv"
batch_df = pd.read_csv(batch_data)

### set PD options

In [4]:
pd.set_option("display.max_rows", None)

In [5]:
# dtypes
int_columns = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "dosprt", "hltprhc", "Nchanged"]
float_columns = ["bmi", "gower_distance", "risk_before", "predicted_risk_after", "cf_gen_time_sec"]


# Convert and fill NaN with empty strings
batch_df[int_columns] = batch_df[int_columns].astype("Int64").astype("string").fillna("")
batch_df[float_columns] = batch_df[float_columns].round(4).astype("string").fillna("")
batch_df["valid"] = batch_df["valid"].astype("string").fillna("")

In [6]:
batch_df = batch_df.drop(columns=["hltprhc", "target_risk"])
batch_df["cf_id"] = batch_df["cf_id"].replace({"original": "xin"})

In [7]:
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,99.45,,,,0.0633,
1,0,cf_1,,,,,,,16.9409,3,,0.1306,2,False,0.0633,0.0967
2,0,cf_2,,,,,,,15.2291,6,,0.25,2,False,0.0633,0.17
3,0,cf_3,2,2,,,,,,,,0.25,2,False,0.0633,0.1267
4,0,cf_4,,,,,,,17.7551,,,0.041,1,False,0.0633,0.0467
5,0,cf_5,,,,,,,16.5046,,,0.0826,1,False,0.0633,0.0933
6,0,cf_6,,,5,,,,16.1725,,,0.2186,2,False,0.0633,0.0767
7,0,cf_7,,2,5,,,,,,,0.25,2,False,0.0633,0.0533
8,0,cf_8,,,,,,,18.2293,,,0.0252,1,False,0.0633,0.0433
9,0,cf_9,,2,,,,,17.0718,,,0.1887,2,False,0.0633,0.16
10,0,cf_10,,,,,,,17.7062,1,,0.0634,2,False,0.0633,0.0667
11,1,xin,3,4,1,2,3,0,22.3757,0,98.56,,,,0.1467,
12,1,cf_1,,,6,,,,19.6497,,,0.1948,2,False,0.1467,0.1567
13,1,cf_2,,,,4,,,19.2603,,,0.1298,2,True,0.1467,0.0267
14,1,cf_3,,,3,,1,,,,,0.175,2,False,0.1467,0.1367
15,1,cf_4,,,,,,,17.9392,1,,0.1449,2,False,0.1467,0.1033
16,1,cf_5,,,,7,,,18.8498,,,0.2153,2,False,0.1467,0.16
17,1,cf_6,,,,,,,17.4949,,,0.125,1,False,0.1467,0.2
18,1,cf_7,,,,,,,21.1522,,,0.0313,1,False,0.1467,0.2433
19,1,cf_8,,,,,,,18.3319,4,,0.2286,2,False,0.1467,0.1067
20,1,cf_9,,,3,7,,,,,,0.175,2,False,0.1467,0.19
21,1,cf_10,,,,,,,22.1399,,,0.006,1,False,0.1467,0.1233
22,2,xin,5,3,1,1,4,0,22.694,7,133.88,,,,0.1567,
23,2,cf_1,,,,,,,19.3598,,,0.057,1,False,0.1567,0.2367
24,2,cf_2,,,,,,,17.6753,,,0.0858,1,False,0.1567,0.22
25,2,cf_3,,,,,2,,18.1389,,,0.2028,2,False,0.1567,0.1067
26,2,cf_4,,,6,,,,16.9904,,,0.2225,2,False,0.1567,0.1333
27,2,cf_5,2,,,,,,,,,0.125,1,True,0.1567,0.0733
28,2,cf_6,,,,,,,22.6557,,,0.0007,1,False,0.1567,0.1567
29,2,cf_7,,,,5,,,17.7903,,,0.2088,2,False,0.1567,0.2
30,2,cf_8,,,,,,,21.7431,,,0.0163,1,False,0.1567,0.19
31,2,cf_9,,,,,,,18.0719,,,0.079,1,False,0.1567,0.2233
32,2,cf_10,,,,,,,15.3793,,,0.125,1,False,0.1567,0.2033
33,3,xin,3,3,6,6,2,0,24.3418,1,97.63,,,,0.02,
34,3,cf_1,,,,,,,20.2869,2,,0.1886,2,False,0.02,0.08
35,3,cf_2,,,,,,,21.4369,,,0.0456,1,False,0.02,0.0167
36,3,cf_3,,,,,1,,18.0197,,,0.2242,2,False,0.02,0.1851
37,3,cf_4,,,,,,,19.5435,,,0.0753,1,False,0.02,0.0614
38,3,cf_5,,,,,,,22.1465,,,0.0344,1,False,0.02,0.0833
39,3,cf_6,1,,,,,,23.7361,,,0.1345,2,False,0.02,0.24
40,3,cf_7,,,,,,,17.1118,,,0.1134,1,False,0.02,0.0481
41,3,cf_8,,,,,1,,19.5481,,,0.2002,2,False,0.02,0.174
42,3,cf_9,,,,,,,16.3733,,,0.125,1,False,0.02,0.0881
43,3,cf_10,,,,,,,21.1923,,,0.0494,1,False,0.02,0.0167
44,4,xin,5,4,2,7,1,0,21.2585,3,99.39,,,,0.0267,
45,4,cf_1,,,,,,,21.0769,,,0.0037,1,False,0.0267,0.0167
46,4,cf_2,,,,,,,17.278,,,0.0813,1,False,0.0267,0.04
47,4,cf_3,,,,,,,15.1414,,,0.125,1,False,0.0267,0.0733
48,4,cf_4,,,,,,,19.385,,,0.0383,1,False,0.0267,0.0367
49,4,cf_5,,,,,,,17.8838,,,0.069,1,False,0.0267,0.04
50,4,cf_6,,,,,,,15.3035,,,0.1217,1,False,0.0267,0.0733
51,4,cf_7,,,,,,,17.504,7,,0.2017,2,False,0.0267,0.06
52,4,cf_8,,,,,,,15.5995,5,,0.1781,2,False,0.0267,0.05
53,4,cf_9,,,,,,,16.5037,7,,0.2222,2,False,0.0267,0.0633
54,4,cf_10,,,,,,,18.0017,,,0.0666,1,False,0.0267,0.04
55,5,xin,2,2,1,2,4,0,27.9904,0,0.32,,,,0.3267,
56,5,cf_1,,,,,,,25.4227,6,,0.133,2,True,0.3267,0.1133
57,5,cf_2,,,,,,,18.0616,,,0.0999,1,False,0.3267,0.1767
58,5,cf_3,,,,,2,,16.5203,,,0.2404,2,False,0.3267,0.1867
59,5,cf_4,,,,,,,,5,,0.0893,1,True,0.3267,0.0767
60,5,cf_5,,,3,,,,,7,,0.2083,2,False,0.3267,0.2367
61,5,cf_6,,,,,,,15.5681,,,0.125,1,False,0.3267,0.1967
62,5,cf_7,,,4,,,,18.8217,,,0.2173,2,False,0.3267,0.2233
63,5,cf_8,,,,,,,20.4999,,,0.0754,1,False,0.3267,0.2233
64,5,cf_9,,,,,,,21.8563,,,0.0617,1,False,0.3267,0.22
65,5,cf_10,,,,3,2,,,,,0.25,2,True,0.3267,0.1333
66,6,xin,2,3,5,4,1,0,27.6817,4,100.37,,,,0.1467,
67,6,cf_1,,,,,,,21.6414,,,0.0867,1,True,0.1467,0.0033
68,6,cf_2,,,6,7,,,,,,0.25,2,True,0.1467,0.01
69,6,cf_3,,,,,,,21.4948,,,0.0888,1,True,0.1467,0.0
70,6,cf_4,,,,5,,,,,,0.0417,1,True,0.1467,0.0633
71,6,cf_5,,,,,,,25.6028,,,0.0298,1,True,0.1467,0.0667
72,6,cf_6,,,,,,,21.9159,,,0.0828,1,True,0.1467,0.0125
73,6,cf_7,,,,,,,27.1901,5,,0.1321,2,False,0.1467,0.2067
74,6,cf_8,,,6,,,,,,,0.125,1,False,0.1467,0.08
75,6,cf_9,,,6,,,,19.0104,,,0.2495,2,True,0.1467,0.0133
76,6,cf_10,,,,,,,18.9736,,,0.125,1,True,0.1467,0.02
77,7,xin,2,3,6,3,1,0,20.4382,2,398.59,,,,0.0133,
78,7,cf_1,,,,,,,20.3118,,,0.0056,1,False,0.0133,0.0133
79,7,cf_2,,2,,,,,19.3986,,,0.1086,2,True,0.0133,0.0
80,7,cf_3,,,,,,,18.5866,,,0.0822,1,True,0.0133,0.0033
81,7,cf_4,,,,,,,19.7046,,,0.0326,1,True,0.0133,0.0
82,7,cf_5,,,,,,,19.8178,,,0.0275,1,True,0.0133,0.0067
83,7,cf_6,,,,,,,18.803,,,0.0726,1,False,0.0133,0.0133
84,7,cf_7,,,,,,,17.6215,,,0.125,1,True,0.0133,0.0033
85,7,cf_8,,1,,,,,18.1406,,,0.227,2,False,0.0133,0.1933
86,7,cf_9,,2,,,,,,7,,0.1875,2,True,0.0133,0.0067
87,7,cf_10,1,,,,,,20.2108,,,0.1351,2,False,0.0133,0.0567
88,8,xin,6,4,1,1,1,0,26.0146,0,0.32,,,,0.09,
89,8,cf_1,,,,,,,17.6862,,,0.125,1,False,0.09,0.0833
90,8,cf_2,4,,,,,,,3,,0.2,2,True,0.09,0.01
91,8,cf_3,,,6,2,,,,,,0.25,2,False,0.09,0.05
92,8,cf_4,,,,,,,20.7897,,,0.0784,1,False,0.09,0.095
93,8,cf_5,,,6,,,,,4,,0.225,2,False,0.09,0.0833
94,8,cf_6,,,,,,,24.2444,5,,0.1516,2,True,0.09,0.02
95,8,cf_7,,2,5,,,,,,,0.1833,2,False,0.09,0.2067
96,8,cf_8,,1,,,,,,,,0.125,1,False,0.09,0.17
97,8,cf_9,,1,,,,,20.1182,,,0.2135,2,False,0.09,0.1017
98,8,cf_10,,,6,,,,,5,,0.25,2,True,0.09,0.0367

In [8]:
from cf_bench.utils import select_one_cf_per_query

# Select one CF per observation
# prefers valid CFs without violations, and lowest Gower
single_cf_df = select_one_cf_per_query(batch_df)
single_cf_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,99.45,,,,0.0633,
9,0,cf_1,,,,,,,16.9409,3,,0.1306,2,False,0.0633,0.0967
1,1,xin,3,4,1,2,3,0,22.3757,0,98.56,,,,0.1467,
10,1,cf_2,,,,4,,,19.2603,,,0.1298,2,True,0.1467,0.0267
2,2,xin,5,3,1,1,4,0,22.694,7,133.88,,,,0.1567,
11,2,cf_5,2,,,,,,,,,0.125,1,True,0.1567,0.0733
3,3,xin,3,3,6,6,2,0,24.3418,1,97.63,,,,0.02,
12,3,cf_1,,,,,,,20.2869,2,,0.1886,2,False,0.02,0.08
4,4,xin,5,4,2,7,1,0,21.2585,3,99.39,,,,0.0267,
13,4,cf_1,,,,,,,21.0769,,,0.0037,1,False,0.0267,0.0167
5,5,xin,2,2,1,2,4,0,27.9904,0,0.32,,,,0.3267,
14,5,cf_4,,,,,,,,5,,0.0893,1,True,0.3267,0.0767
6,6,xin,2,3,5,4,1,0,27.6817,4,100.37,,,,0.1467,
15,6,cf_5,,,,,,,25.6028,,,0.0298,1,True,0.1467,0.0667
7,7,xin,2,3,6,3,1,0,20.4382,2,398.59,,,,0.0133,
16,7,cf_5,,,,,,,19.8178,,,0.0275,1,True,0.0133,0.0067
8,8,xin,6,4,1,1,1,0,26.0146,0,0.32,,,,0.09,
17,8,cf_6,,,,,,,24.2444,5,,0.1516,2,True,0.09,0.02