In [1]:
import os
from pathlib import Path

import numpy as np
import pandas as pd

from dotenv import load_dotenv

load_dotenv()

CF_OUTPUTS = Path(os.getenv("CF_OUTPUTS"))
print(CF_OUTPUTS)
print(CF_OUTPUTS.is_dir())

/home/dyretna/Dokument/Code/GitHub/nightingale_projects/cf_bench/cf_outputs
True

In [2]:
GEN_1_RANDOM = CF_OUTPUTS / "gen1_models_explainers_constraints" / "random_search_exp"
GEN_1_RANDOM.is_dir()

True

In [3]:
batch_data = GEN_1_RANDOM / "XGB_prange_highthres_2026-04-17" / "annotated.csv"
batch_df = pd.read_csv(batch_data)

### set PD options

In [4]:
pd.set_option("display.max_rows", None)

In [5]:
# dtypes
int_columns = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "dosprt", "hltprhc", "Nchanged"]
float_columns = ["bmi", "gower_distance", "risk_before", "predicted_risk_after", "cf_gen_time_sec"]


# Convert and fill NaN with empty strings
batch_df[int_columns] = batch_df[int_columns].astype("Int64").astype("string").fillna("")
batch_df[float_columns] = batch_df[float_columns].round(4).astype("string").fillna("")
batch_df["valid"] = batch_df["valid"].astype("string").fillna("")

In [6]:
batch_df = batch_df.drop(columns=["hltprhc", "target_risk"])
batch_df["cf_id"] = batch_df["cf_id"].replace({"original": "xin"})

In [7]:
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,84.0,,,,0.026,
1,0,cf_1,,,5,,,,15.1784,,,0.2446,2,True,0.026,0.0022
2,0,cf_2,,1,5,,,,,,,0.25,2,True,0.026,0.0045
3,0,cf_3,,,,,,,15.6601,,,0.1044,1,True,0.026,0.004
4,0,cf_4,1,,,,,,18.1644,,,0.1508,2,False,0.026,0.0431
5,0,cf_5,3,,,,,,16.0498,,,0.1339,2,True,0.026,0.0095
6,0,cf_6,,,,7,,,18.7952,,,0.131,2,False,0.026,0.0707
7,0,cf_7,1,2,,,,,,,,0.1875,2,False,0.026,0.0337
8,0,cf_8,,,,6,,,16.1217,,,0.1733,2,False,0.026,0.0347
9,0,cf_9,,,,,,,15.0933,1,,0.2472,2,True,0.026,0.003
10,0,cf_10,,,,5,,,15.0056,,,0.1667,2,True,0.026,0.0095
11,1,xin,3,4,1,2,3,0,22.3757,0,0.19,,,,0.2497,
12,1,cf_1,,,,,,,19.9925,,,0.071,1,True,0.2497,0.0963
13,1,cf_2,,,,,,,18.1778,,,0.125,1,True,0.2497,0.0486
14,1,cf_3,,,,,,,18.6589,,,0.1107,1,True,0.2497,0.0584
15,1,cf_4,,,,4,,,,,,0.05,1,True,0.2497,0.0782
16,1,cf_5,,,,7,,,,4,,0.2083,2,False,0.2497,0.1502
17,1,cf_6,,,,,,,20.1667,5,,0.1699,2,False,0.2497,0.1366
18,1,cf_7,,,,,,,19.9073,,,0.0735,1,True,0.2497,0.029
19,1,cf_8,,3,,,,,,6,,0.25,2,True,0.2497,0.1213
20,1,cf_9,,,,,,,19.5716,,,0.0835,1,True,0.2497,0.0769
21,1,cf_10,,,2,,,,,2,,0.1667,2,True,0.2497,0.1073
22,2,xin,5,3,1,1,4,0,22.694,7,0.23,,,,0.218,
23,2,cf_1,,,,,,,17.6974,,,0.0937,1,True,0.218,0.0195
24,2,cf_2,,,2,,,,,,,0.125,1,False,0.218,0.1561
25,2,cf_3,,,,,,,21.2092,,,0.0278,1,False,0.218,0.1674
26,2,cf_4,1,,,,,,21.4746,,,0.1479,2,True,0.218,0.0384
27,2,cf_5,1,,,5,,,,,,0.2083,2,False,0.218,0.1486
28,2,cf_6,,,,7,,,16.5482,,,0.2402,2,True,0.218,0.0062
29,2,cf_7,,,,,,,21.4391,,,0.0235,1,False,0.218,0.2402
30,2,cf_8,,,,,,,20.7906,,,0.0357,1,True,0.218,0.1046
31,2,cf_9,,,,,,,17.0812,,,0.1052,1,True,0.218,0.0108
32,2,cf_10,,,,,,,16.0266,,,0.125,1,True,0.218,0.0108
33,3,xin,3,3,6,6,2,0,24.3418,1,92.97,,,,0.0653,
34,3,cf_1,,,,,,,20.2344,,,0.0567,1,False,0.0653,0.1986
35,3,cf_2,,,,,,,19.3846,,,0.0684,1,False,0.0653,0.1588
36,3,cf_3,,,,,,,23.0629,,,0.0177,1,False,0.0653,0.1389
37,3,cf_4,,,,,,,19.5439,,,0.0662,1,False,0.0653,0.1008
38,3,cf_5,,,,,,,23.9439,,,0.0055,1,False,0.0653,0.1116
39,3,cf_6,,,,,,,23.1153,7,,0.1419,2,True,0.0653,0.0318
40,3,cf_7,,,,,,,22.1535,,,0.0302,1,False,0.0653,0.1213
41,3,cf_8,2,,,,,,19.7797,,,0.188,2,False,0.0653,0.0731
42,3,cf_9,,,,,,,15.2866,,,0.125,1,True,0.0653,0.0152
43,3,cf_10,,,,,,,24.0148,,,0.0045,1,False,0.0653,0.1545
44,4,xin,5,4,2,7,1,0,21.2585,3,92.58,,,,0.0811,
45,4,cf_1,,,,,,,,4,,0.125,1,False,0.0811,0.0473
46,4,cf_2,,,,,,,18.5028,,,0.1093,1,True,0.0811,0.0005
47,4,cf_3,1,,,,,,19.2337,,,0.2053,2,True,0.0811,0.0057
48,4,cf_4,,,,,,,21.1494,,,0.0043,1,True,0.0811,0.0057
49,4,cf_5,,,,,,,21.2361,,,0.0009,1,True,0.0811,0.0141
50,4,cf_6,,,,,,,20.9751,,,0.0112,1,True,0.0811,0.005
51,4,cf_7,,1,,,,,,4,,0.25,2,True,0.0811,0.0083
52,4,cf_8,,,,,,,19.0256,,,0.0885,1,True,0.0811,0.0001
53,4,cf_9,4,,,,,,18.416,,,0.1439,2,True,0.0811,0.0004
54,4,cf_10,,,3,,,,18.1057,,,0.25,2,True,0.0811,0.0
55,5,xin,2,2,1,2,4,0,27.9904,0,0.2,,,,0.0484,
56,5,cf_1,,,,,,,16.203,,,0.125,1,True,0.0484,0.0092
57,5,cf_2,,,,,,,20.2711,,,0.0819,1,True,0.0484,0.0176
58,5,cf_3,,,,,1,,21.9156,,,0.1894,2,True,0.0484,0.0096
59,5,cf_4,,,,,,,22.9548,6,,0.1605,2,False,0.0484,0.0712
60,5,cf_5,,,2,,,,,6,,0.2321,2,True,0.0484,0.0241
61,5,cf_6,,,,,,,26.44,,,0.0164,1,False,0.0484,0.1208
62,5,cf_7,,,,3,3,,,,,0.0833,2,False,0.0484,0.2037
63,5,cf_8,,,,5,,,,3,,0.1786,2,False,0.0484,0.0599
64,5,cf_9,,,,3,,,,3,,0.0952,2,False,0.0484,0.0658
65,5,cf_10,,,,,,,16.2718,7,,0.2493,2,True,0.0484,0.017
66,6,xin,2,3,5,4,1,0,27.6817,4,42.04,,,,0.0539,
67,6,cf_1,1,,,,,,,6,,0.2083,2,False,0.0539,0.1222
68,6,cf_2,,,,7,,,17.9809,,,0.2381,2,True,0.0539,0.0011
69,6,cf_3,,,6,,,,26.7962,,,0.1353,2,True,0.0539,0.0143
70,6,cf_4,,,,,,,26.1456,,,0.0179,1,True,0.0539,0.0244
71,6,cf_5,,,,,,,19.3925,,,0.0967,1,True,0.0539,0.0239
72,6,cf_6,,,,,,,21.7275,7,,0.1944,2,True,0.0539,0.0065
73,6,cf_7,,,,6,,,24.5894,,,0.1194,2,True,0.0539,0.0261
74,6,cf_8,,,,,,,25.9452,,,0.0202,1,False,0.0539,0.0702
75,6,cf_9,,,,,,,16.9617,,,0.125,1,True,0.0539,0.0012
76,6,cf_10,,,,,,,25.8378,,,0.0215,1,False,0.0539,0.0466
77,7,xin,2,3,6,3,1,0,20.4382,2,122.97,,,,0.0565,
78,7,cf_1,,,,,,,20.2971,,,0.0033,1,False,0.0565,0.1069
79,7,cf_2,,,,,,,16.4976,,,0.0919,1,True,0.0565,0.0003
80,7,cf_3,,2,,,,,,3,,0.25,2,True,0.0565,0.0087
81,7,cf_4,,,,,,,20.1464,,,0.0068,1,True,0.0565,0.0209
82,7,cf_5,,,,,,,18.3662,,,0.0483,1,True,0.0565,0.0029
83,7,cf_6,,,,5,,,15.3655,,,0.2433,2,True,0.0565,0.0095
84,7,cf_7,,,,,,,19.6972,,,0.0173,1,True,0.0565,0.0078
85,7,cf_8,,,,4,,,15.0774,,,0.1875,2,True,0.0565,0.0018
86,7,cf_9,,,,,,,17.9147,,,0.0588,1,True,0.0565,0.0003
87,7,cf_10,,,,,,,18.1568,,,0.0532,1,True,0.0565,0.0007
88,8,xin,6,4,1,1,1,0,26.0146,0,0.18,,,,0.1216,
89,8,cf_1,,,,,,,20.4934,,,0.0646,1,False,0.1216,0.0657
90,8,cf_2,,,,,,,18.8822,,,0.0835,1,True,0.1216,0.0032
91,8,cf_3,4,,3,,,,,,,0.175,2,False,0.1216,0.2185
92,8,cf_4,,,,7,,,,,,0.125,1,False,0.1216,0.1639
93,8,cf_5,,,,,,,19.8626,,,0.072,1,True,0.1216,0.0039
94,8,cf_6,,,2,,,,19.7193,,,0.1362,2,True,0.1216,0.001
95,8,cf_7,,,,3,,,15.3319,,,0.1667,2,True,0.1216,0.0007
96,8,cf_8,,,,,,,19.7252,,,0.0736,1,True,0.1216,0.0135
97,8,cf_9,1,,,,,,15.692,,,0.2458,2,True,0.1216,0.0022
98,8,cf_10,3,,,,,,,6,,0.2,2,False,0.1216,0.139

In [8]:
from cf_bench.utils import select_one_cf_per_query

# Select one CF per observation
# prefers valid CFs without violations, and lowest Gower
single_gower_df = select_one_cf_per_query(batch_df, selector="gower")
single_gower_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,84.0,,,,0.026,
9,0,cf_3,,,,,,,15.6601,,,0.1044,1,True,0.026,0.004
1,1,xin,3,4,1,2,3,0,22.3757,0,0.19,,,,0.2497,
10,1,cf_4,,,,4,,,,,,0.05,1,True,0.2497,0.0782
2,2,xin,5,3,1,1,4,0,22.694,7,0.23,,,,0.218,
11,2,cf_8,,,,,,,20.7906,,,0.0357,1,True,0.218,0.1046
3,3,xin,3,3,6,6,2,0,24.3418,1,92.97,,,,0.0653,
12,3,cf_9,,,,,,,15.2866,,,0.125,1,True,0.0653,0.0152
4,4,xin,5,4,2,7,1,0,21.2585,3,92.58,,,,0.0811,
13,4,cf_5,,,,,,,21.2361,,,0.0009,1,True,0.0811,0.0141
5,5,xin,2,2,1,2,4,0,27.9904,0,0.2,,,,0.0484,
14,5,cf_2,,,,,,,20.2711,,,0.0819,1,True,0.0484,0.0176
6,6,xin,2,3,5,4,1,0,27.6817,4,42.04,,,,0.0539,
15,6,cf_4,,,,,,,26.1456,,,0.0179,1,True,0.0539,0.0244
7,7,xin,2,3,6,3,1,0,20.4382,2,122.97,,,,0.0565,
16,7,cf_4,,,,,,,20.1464,,,0.0068,1,True,0.0565,0.0209
8,8,xin,6,4,1,1,1,0,26.0146,0,0.18,,,,0.1216,
17,8,cf_5,,,,,,,19.8626,,,0.072,1,True,0.1216,0.0039

In [9]:
# Random selection (Gower may pick only BMI variations)
single_random_df = select_one_cf_per_query(batch_df, selector="random")
single_random_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,84.0,,,,0.026,
9,0,cf_1,,,5,,,,15.1784,,,0.2446,2,True,0.026,0.0022
1,1,xin,3,4,1,2,3,0,22.3757,0,0.19,,,,0.2497,
10,1,cf_2,,,,,,,18.1778,,,0.125,1,True,0.2497,0.0486
2,2,xin,5,3,1,1,4,0,22.694,7,0.23,,,,0.218,
11,2,cf_1,,,,,,,17.6974,,,0.0937,1,True,0.218,0.0195
3,3,xin,3,3,6,6,2,0,24.3418,1,92.97,,,,0.0653,
12,3,cf_9,,,,,,,15.2866,,,0.125,1,True,0.0653,0.0152
4,4,xin,5,4,2,7,1,0,21.2585,3,92.58,,,,0.0811,
13,4,cf_9,4,,,,,,18.416,,,0.1439,2,True,0.0811,0.0004
5,5,xin,2,2,1,2,4,0,27.9904,0,0.2,,,,0.0484,
14,5,cf_2,,,,,,,20.2711,,,0.0819,1,True,0.0484,0.0176
6,6,xin,2,3,5,4,1,0,27.6817,4,42.04,,,,0.0539,
15,6,cf_2,,,,7,,,17.9809,,,0.2381,2,True,0.0539,0.0011
7,7,xin,2,3,6,3,1,0,20.4382,2,122.97,,,,0.0565,
16,7,cf_9,,,,,,,17.9147,,,0.0588,1,True,0.0565,0.0003
8,8,xin,6,4,1,1,1,0,26.0146,0,0.18,,,,0.1216,
17,8,cf_2,,,,,,,18.8822,,,0.0835,1,True,0.1216,0.0032