In [1]:
import os
from pathlib import Path

import numpy as np
import pandas as pd

from dotenv import load_dotenv

load_dotenv()

CF_OUTPUTS = Path(os.getenv("CF_OUTPUTS"))
print(CF_OUTPUTS)
print(CF_OUTPUTS.is_dir())

/home/dyretna/Dokument/Code/GitHub/nightingale_projects/cf_bench/cf_outputs
True

In [2]:
GEN_1_RANDOM = CF_OUTPUTS / "gen1_models_explainers_constraints" / "random_search_exp"
GEN_1_RANDOM.is_dir()

True

In [3]:
batch_data = GEN_1_RANDOM / "RF_highthres_2026-04-21" / "annotated.csv"
batch_df = pd.read_csv(batch_data)

### set PD options

In [4]:
pd.set_option("display.max_rows", None)

In [5]:
# dtypes
int_columns = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "dosprt", "hltprhc", "Nchanged"]
float_columns = ["bmi", "gower_distance", "risk_before", "predicted_risk_after", "cf_gen_time_sec"]


# Convert and fill NaN with empty strings
batch_df[int_columns] = batch_df[int_columns].astype("Int64").astype("string").fillna("")
batch_df[float_columns] = batch_df[float_columns].round(4).astype("string").fillna("")
batch_df["valid"] = batch_df["valid"].astype("string").fillna("")

In [6]:
batch_df = batch_df.drop(columns=["hltprhc", "target_risk"])
batch_df["cf_id"] = batch_df["cf_id"].replace({"original": "xin"})

In [7]:
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,0.34,,,,0.0633,
1,0,cf_1,,,,,,,17.1346,,,0.0115,1,False,0.0633,0.0467
2,0,cf_2,,,,,,,30.1683,,,0.0695,1,False,0.0633,0.1133
3,0,cf_3,7,,,,,,16.9519,,,0.1376,2,False,0.0633,0.0833
4,0,cf_4,,6,,,,,27.877,,,0.149,2,False,0.0633,0.1967
5,0,cf_5,,4,1,,,,,,,0.1562,2,True,0.0633,0.03
6,0,cf_6,,2,,,,1,,,,0.1562,2,False,0.0633,0.11
7,0,cf_7,,,,,,1,37.0705,,,0.2374,2,False,0.0633,0.09
8,0,cf_8,5,,,,,,29.8874,,,0.1094,2,False,0.0633,0.06
9,0,cf_9,,,,,,,33.6511,,,0.0911,1,False,0.0633,0.2233
10,0,cf_10,5,,,,,,29.9768,,,0.11,2,False,0.0633,0.07
11,1,xin,3,4,1,2,3,0,22.3757,0,0.33,,,,0.1467,
12,1,cf_1,,,,,,,32.3425,,,0.0869,1,False,0.1467,0.12
13,1,cf_2,,,,,,1,,,,0.125,1,True,0.1467,0.0733
14,1,cf_3,,,,3,,1,,,,0.1667,2,True,0.1467,0.0467
15,1,cf_4,,,6,,2,,,,,0.25,2,False,0.1467,0.1467
16,1,cf_5,,,,,,,33.832,5,,0.1891,2,False,0.1467,0.0833
17,1,cf_6,,,,,,,30.1757,,,0.068,1,False,0.1467,0.1667
18,1,cf_7,,,,,2,,21.1455,,,0.1357,2,False,0.1467,0.09
19,1,cf_8,,,,5,,,,,,0.125,1,True,0.1467,0.0667
20,1,cf_9,,,,,,,35.4895,,,0.1143,1,False,0.1467,0.1533
21,1,cf_10,,7,,,,,,7,,0.25,2,False,0.1467,0.1867
22,2,xin,5,3,1,1,4,0,22.694,7,0.32,,,,0.1567,
23,2,cf_1,,,,,,,34.7006,,,0.1112,1,False,0.1567,0.0967
24,2,cf_2,,,,,,,26.8578,,,0.0386,1,True,0.1567,0.07
25,2,cf_3,,,,6,,,,1,,0.25,2,False,0.1567,0.2433
26,2,cf_4,,,,5,,,33.5562,,,0.2006,2,False,0.1567,0.11
27,2,cf_5,,,,,,1,34.1262,,,0.2309,2,False,0.1567,0.1367
28,2,cf_6,,,,,,,36.1941,,,0.125,1,False,0.1567,0.16
29,2,cf_7,,,5,4,,,,,,0.2,2,False,0.1567,0.1833
30,2,cf_8,,,,,1,1,,,,0.25,2,True,0.1567,0.02
31,2,cf_9,,,,,,,34.2729,,,0.1072,1,False,0.1567,0.0833
32,2,cf_10,,,,,,1,34.7493,,,0.2366,2,False,0.1567,0.1467
33,3,xin,3,3,6,6,2,0,24.3418,1,0.34,,,,0.02,
34,3,cf_1,,,,,,,17.9625,4,,0.132,2,False,0.02,0.1867
35,3,cf_2,4,,4,,,,,,,0.1125,2,False,0.02,0.1208
36,3,cf_3,,,1,,3,,,,,0.25,2,False,0.02,0.1433
37,3,cf_4,,,,5,,,20.7487,,,0.1465,2,False,0.02,0.1658
38,3,cf_5,,,,,,,38.8273,,,0.0868,1,False,0.02,0.11
39,3,cf_6,,7,,,,,,,,0.125,1,False,0.02,0.1167
40,3,cf_7,,4,,,,,31.7405,,,0.0756,2,False,0.02,0.1033
41,3,cf_8,,,3,,,,22.7459,,,0.0846,2,False,0.02,0.12
42,3,cf_9,,,,,,,27.434,,,0.0185,1,False,0.02,0.0533
43,3,cf_10,5,,,,,,,5,,0.25,2,False,0.02,0.0967
44,4,xin,5,4,2,7,1,0,21.2585,3,0.33,,,,0.0267,
45,4,cf_1,,,,4,,,,7,,0.1583,2,False,0.0267,0.02
46,4,cf_2,,,,3,4,,,,,0.225,2,False,0.0267,0.07
47,4,cf_3,,,5,,,1,,,,0.25,2,False,0.0267,0.0233
48,4,cf_4,,,3,2,,,,,,0.1667,2,True,0.0267,0.0033
49,4,cf_5,4,2,,,,,,,,0.125,2,True,0.0267,0.01
50,4,cf_6,2,,,5,,,,,,0.175,2,False,0.0267,0.04
51,4,cf_7,,,,,,,36.914,1,,0.1476,2,False,0.0267,0.0967
52,4,cf_8,,,,,,1,39.7272,,,0.25,2,False,0.0267,0.14
53,4,cf_9,,2,,4,,,,,,0.1583,2,False,0.0267,0.03
54,4,cf_10,4,5,,,,,,,,0.0833,2,False,0.0267,0.0167
55,5,xin,2,2,1,2,4,0,27.9904,0,99.06,,,,0.3267,
56,5,cf_1,,,,,1,,39.3885,,,0.1926,2,True,0.3267,0.1633
57,5,cf_2,,,,3,,,,7,,0.15,2,True,0.3267,0.0367
58,5,cf_3,,,,,,,28.5716,2,,0.0392,2,True,0.3267,0.1433
59,5,cf_4,,1,,7,,,,,,0.25,2,False,0.3267,0.2467
60,5,cf_5,,,,,1,,23.863,,,0.1495,2,True,0.3267,0.0467
61,5,cf_6,7,,,,1,,,,,0.25,2,True,0.3267,0.0433
62,5,cf_7,,,,,,,18.3044,,,0.0574,1,False,0.3267,0.1833
63,5,cf_8,,,3,,,,,3,,0.1036,2,False,0.3267,0.2167
64,5,cf_9,,,,6,,,,3,,0.1536,2,True,0.3267,0.13
65,5,cf_10,,,6,,,,22.8962,,,0.1552,2,False,0.3267,0.1767
66,6,xin,2,3,5,4,1,0,27.6817,4,0.33,,,,0.1467,
67,6,cf_1,,7,,,,,,7,,0.1625,2,False,0.1467,0.1267
68,6,cf_2,4,,,7,,,,,,0.1875,2,True,0.1467,0.01
69,6,cf_3,,2,3,,,,,,,0.0875,2,False,0.1467,0.1033
70,6,cf_4,,,2,2,,,,,,0.1354,2,True,0.1467,0.0633
71,6,cf_5,,,,,,,31.389,,,0.0348,1,False,0.1467,0.21
72,6,cf_6,,,,1,4,,,,,0.1875,2,False,0.1467,0.1933
73,6,cf_7,,,3,,,,18.0556,,,0.1527,2,True,0.1467,0.0033
74,6,cf_8,,,,6,,,,1,,0.1042,2,False,0.1467,0.0833
75,6,cf_9,,,,,3,,,2,,0.125,2,False,0.1467,0.1033
76,6,cf_10,,,6,,4,,,,,0.1562,2,False,0.1467,0.1467
77,7,xin,2,3,6,3,1,0,20.4382,2,99.47,,,,0.0133,
78,7,cf_1,,,4,,,,,1,,0.1458,2,True,0.0133,0.0067
79,7,cf_2,,,,,,,20.0401,,,0.0031,1,False,0.0133,0.01
80,7,cf_3,,,,,,,33.0802,,,0.0969,1,False,0.0133,0.0467
81,7,cf_4,1,,5,,,,,,,0.1875,2,False,0.0133,0.0933
82,7,cf_5,,,,,4,,28.6382,,,0.1879,2,False,0.0133,0.0778
83,7,cf_6,,,,5,,,,6,,0.2083,2,False,0.0133,0.1133
84,7,cf_7,,,,,4,,18.8432,,,0.1372,2,False,0.0133,0.0492
85,7,cf_8,,,4,,,,35.146,,,0.2378,2,False,0.0133,0.1567
86,7,cf_9,,,4,,,,,7,,0.2292,2,False,0.0133,0.02
87,7,cf_10,,,,,,,30.4791,,,0.077,1,False,0.0133,0.0733
88,8,xin,6,4,1,1,1,0,26.0146,0,100.59,,,,0.09,
89,8,cf_1,,,,,,,29.9656,,,0.0236,1,False,0.09,0.09
90,8,cf_2,,,,,,,17.7046,1,,0.0704,2,False,0.09,0.0967
91,8,cf_3,1,2,,,,,,,,0.1875,2,False,0.09,0.14
92,8,cf_4,,,,6,,,18.8192,,,0.1679,2,False,0.09,0.0933
93,8,cf_5,,6,,,,,38.6624,,,0.1379,2,False,0.09,0.1967
94,8,cf_6,,,,3,,,,4,,0.1333,2,True,0.09,0.0
95,8,cf_7,,,,5,,,19.639,,,0.138,2,True,0.09,0.0133
96,8,cf_8,,,,,,,25.0996,,,0.0055,1,True,0.09,0.0367
97,8,cf_9,,,5,,2,,,,,0.25,2,False,0.09,0.06
98,8,cf_10,5,,,,,,,6,,0.15,2,True,0.09,0.03

In [8]:
from cf_bench.utils import select_one_cf_per_query

# Select one CF per observation
# prefers valid CFs without violations, and lowest Gower
single_gower_df = select_one_cf_per_query(batch_df, selector="gower")
single_gower_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,0.34,,,,0.0633,
9,0,cf_5,,4,1,,,,,,,0.1562,2,True,0.0633,0.03
1,1,xin,3,4,1,2,3,0,22.3757,0,0.33,,,,0.1467,
10,1,cf_2,,,,,,1,,,,0.125,1,True,0.1467,0.0733
2,2,xin,5,3,1,1,4,0,22.694,7,0.32,,,,0.1567,
11,2,cf_2,,,,,,,26.8578,,,0.0386,1,True,0.1567,0.07
3,3,xin,3,3,6,6,2,0,24.3418,1,0.34,,,,0.02,
12,3,cf_1,,,,,,,17.9625,4,,0.132,2,False,0.02,0.1867
4,4,xin,5,4,2,7,1,0,21.2585,3,0.33,,,,0.0267,
13,4,cf_5,4,2,,,,,,,,0.125,2,True,0.0267,0.01
5,5,xin,2,2,1,2,4,0,27.9904,0,99.06,,,,0.3267,
14,5,cf_3,,,,,,,28.5716,2,,0.0392,2,True,0.3267,0.1433
6,6,xin,2,3,5,4,1,0,27.6817,4,0.33,,,,0.1467,
15,6,cf_4,,,2,2,,,,,,0.1354,2,True,0.1467,0.0633
7,7,xin,2,3,6,3,1,0,20.4382,2,99.47,,,,0.0133,
16,7,cf_1,,,4,,,,,1,,0.1458,2,True,0.0133,0.0067
8,8,xin,6,4,1,1,1,0,26.0146,0,100.59,,,,0.09,
17,8,cf_8,,,,,,,25.0996,,,0.0055,1,True,0.09,0.0367

In [9]:
# Random selection (Gower may pick only BMI variations)
single_random_df = select_one_cf_per_query(batch_df, selector="random")
single_random_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,0.34,,,,0.0633,
9,0,cf_5,,4,1,,,,,,,0.1562,2,True,0.0633,0.03
1,1,xin,3,4,1,2,3,0,22.3757,0,0.33,,,,0.1467,
10,1,cf_2,,,,,,1,,,,0.125,1,True,0.1467,0.0733
2,2,xin,5,3,1,1,4,0,22.694,7,0.32,,,,0.1567,
11,2,cf_8,,,,,1,1,,,,0.25,2,True,0.1567,0.02
3,3,xin,3,3,6,6,2,0,24.3418,1,0.34,,,,0.02,
12,3,cf_1,,,,,,,17.9625,4,,0.132,2,False,0.02,0.1867
4,4,xin,5,4,2,7,1,0,21.2585,3,0.33,,,,0.0267,
13,4,cf_5,4,2,,,,,,,,0.125,2,True,0.0267,0.01
5,5,xin,2,2,1,2,4,0,27.9904,0,99.06,,,,0.3267,
14,5,cf_1,,,,,1,,39.3885,,,0.1926,2,True,0.3267,0.1633
6,6,xin,2,3,5,4,1,0,27.6817,4,0.33,,,,0.1467,
15,6,cf_2,4,,,7,,,,,,0.1875,2,True,0.1467,0.01
7,7,xin,2,3,6,3,1,0,20.4382,2,99.47,,,,0.0133,
16,7,cf_1,,,4,,,,,1,,0.1458,2,True,0.0133,0.0067
8,8,xin,6,4,1,1,1,0,26.0146,0,100.59,,,,0.09,
17,8,cf_7,,,,5,,,19.639,,,0.138,2,True,0.09,0.0133