In [1]:
import os
from pathlib import Path

import numpy as np
import pandas as pd

from dotenv import load_dotenv

load_dotenv()

CF_OUTPUTS = Path(os.getenv("CF_OUTPUTS"))
print(CF_OUTPUTS)
print(CF_OUTPUTS.is_dir())

/home/dyretna/Dokument/Code/GitHub/nightingale_projects/cf_bench/cf_outputs
True

In [2]:
GEN_1_GENETIC = CF_OUTPUTS / "gen1_models_explainers_constraints" / "genetic_exp"
GEN_1_GENETIC.is_dir()

True

In [3]:
batch_data = GEN_1_GENETIC / "XGB_highthres_2026-04-17" / "annotated.csv"
batch_df = pd.read_csv(batch_data)

### set PD options

In [4]:
pd.set_option("display.max_rows", None)

In [5]:
# dtypes
int_columns = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "dosprt", "hltprhc", "Nchanged"]
float_columns = ["bmi", "gower_distance", "risk_before", "predicted_risk_after", "cf_gen_time_sec"]


# Convert and fill NaN with empty strings
batch_df[int_columns] = batch_df[int_columns].astype("Int64").astype("string").fillna("")
batch_df[float_columns] = batch_df[float_columns].round(4).astype("string").fillna("")
batch_df["valid"] = batch_df["valid"].astype("string").fillna("")

In [6]:
batch_df = batch_df.drop(columns=["hltprhc", "target_risk"])
batch_df["cf_id"] = batch_df["cf_id"].replace({"original": "xin"})

In [7]:
# correct_cf_idx
# Fix cf_id indexing - group by query_index and number counterfactuals sequentially
def fix_cf_id(df):
    # For each query_index group
    fixed_rows = []
    for query_idx, group in df.groupby('query_index', sort=False):
        group = group.copy()
        # First row is xin (original)
        xin_mask = group['cf_id'] == 'xin'
        cf_mask = ~xin_mask

        # Keep xin rows as is
        xin_rows = group[xin_mask].copy()

        # Fix cf rows
        cf_rows = group[cf_mask].copy()
        if len(cf_rows) > 0:
            # Number them cf_1, cf_2, cf_3, etc.
            cf_rows['cf_id'] = [f'cf_{i+1}' for i in range(len(cf_rows))]

        # Combine back
        fixed_rows.append(xin_rows)
        if len(cf_rows) > 0:
            fixed_rows.append(cf_rows)

    return pd.concat(fixed_rows, ignore_index=True)

In [8]:
batch_df = fix_cf_id(batch_df)
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,1.22,,,,0.026,
1,0,cf_1,,,,,,,18.9866,,,0.0,1,True,0.026,0.0123
2,0,cf_2,,1,5,,1,,18.9866,,,0.2917,4,True,0.026,0.0026
3,0,cf_3,,,6,7,,,18.9745,,,0.2141,3,False,0.026,0.1428
4,0,cf_4,,,5,,,,19.0311,4,,0.2817,3,True,0.026,0.0081
5,0,cf_5,2,4,6,1,,,18.9866,,,0.2792,5,False,0.026,0.0485
6,0,cf_6,2,1,5,,1,,18.9866,,,0.3417,5,True,0.026,0.0037
7,0,cf_7,6,1,5,7,,,18.9866,,,0.2792,5,True,0.026,0.0017
8,0,cf_8,2,,6,5,,,18.9866,5,,0.3208,5,False,0.026,0.0799
9,0,cf_9,1,1,4,,1,,18.9866,,,0.325,5,False,0.026,0.018
10,0,cf_10,1,1,4,,,1,18.9866,,,0.325,5,False,0.026,0.018
11,1,xin,3,4,1,2,3,0,22.3757,0,1.3,,,,0.2497,
12,1,cf_1,,,,,,,22.3757,,,0.0,1,False,0.2497,0.2497
13,1,cf_2,,,,,1,,22.3757,,,0.0833,2,True,0.2497,0.07
14,1,cf_3,2,,,,1,,22.3757,,,0.1458,3,True,0.2497,0.0361
15,1,cf_4,1,,,4,4,,22.3757,,,0.2917,4,True,0.2497,0.01
16,1,cf_5,,2,,,2,,22.3757,2,,0.1274,4,True,0.2497,0.0302
17,1,cf_6,,,,3,1,,22.3863,,,0.2708,3,True,0.2497,0.0534
18,1,cf_7,,1,2,4,,,22.3757,7,,0.35,5,True,0.2497,0.0193
19,1,cf_8,1,6,,4,1,,22.3757,,,0.3833,5,False,0.2497,0.1447
20,1,cf_9,2,,6,,1,,22.3757,5,,0.3601,5,True,0.2497,0.0448
21,2,xin,5,3,1,1,4,0,22.694,7,1.08,,,,0.218,
22,2,cf_1,,,,,,,22.694,,,0.0,1,False,0.218,0.218
23,2,cf_2,3,,,,2,,22.68,,,0.242,3,False,0.218,0.1394
24,2,cf_3,1,,,,2,,22.6757,,,0.3333,3,True,0.218,0.0662
25,2,cf_4,3,,5,4,2,,22.694,,,0.3083,5,True,0.218,0.0348
26,2,cf_5,3,,6,2,1,,22.694,,,0.3333,5,True,0.218,0.0301
27,2,cf_6,4,,6,7,2,,22.694,,,0.3646,5,True,0.218,0.0451
28,2,cf_7,,,2,2,1,,22.68,,,0.267,4,True,0.218,0.0124
29,2,cf_8,3,1,,,1,,22.6757,,,0.4375,4,True,0.218,0.0222
30,2,cf_9,2,,,,2,,22.6757,3,,0.4271,4,True,0.218,0.05
31,3,xin,3,3,6,6,2,0,24.3418,1,1.18,,,,0.0653,
32,3,cf_1,,,,,,,24.3418,,,0.0001,1,False,0.0653,0.0653
33,3,cf_2,,,,,,,24.3418,2,,0.0209,2,False,0.0653,0.0617
34,3,cf_3,1,,,3,,,24.3418,,,0.1459,3,False,0.0653,0.1034
35,3,cf_4,2,,,,,,24.3418,2,,0.0626,3,False,0.0653,0.0452
36,3,cf_5,,,,5,,,24.3418,4,,0.0834,3,False,0.0653,0.0651
37,3,cf_6,4,4,,,,,24.3418,,,0.1667,3,False,0.0653,0.1227
38,3,cf_7,,,,,,,24.3375,3,,0.1666,2,False,0.0653,0.0462
39,3,cf_8,,,3,7,,,24.3418,3,,0.1876,4,False,0.0653,0.0479
40,3,cf_9,2,,,1,,,24.3418,7,,0.2709,4,False,0.0653,0.1235
41,3,cf_10,2,,,7,,,24.3418,4,,0.1251,4,False,0.0653,0.0511
42,4,xin,5,4,2,7,1,0,21.2585,3,1.31,,,,0.0811,
43,4,cf_1,,,,,,,21.2585,,,0.1118,1,True,0.0811,0.0141
44,4,cf_2,,2,5,,,,21.2585,,,0.3618,3,True,0.0811,0.0091
45,4,cf_3,2,3,,,,,21.2585,,,0.2681,3,True,0.0811,0.0271
46,4,cf_4,3,3,,,,,21.2585,,,0.2368,3,True,0.0811,0.0167
47,4,cf_5,1,,4,4,,,21.2585,,,0.3952,4,True,0.0811,0.0232
48,4,cf_6,1,,3,3,,,21.2585,,,0.3785,4,True,0.0811,0.0153
49,4,cf_7,2,2,4,,,,21.2585,,,0.4139,4,True,0.0811,0.0277
50,4,cf_8,4,,,2,2,,21.2585,,,0.3931,4,True,0.0811,0.0174
51,5,xin,2,2,1,2,4,0,27.9904,0,1.19,,,,0.0484,
52,5,cf_1,,,,,,,27.9904,,,0.0,1,False,0.0484,0.0484
53,5,cf_2,,,,3,,,27.9904,6,,0.128,3,True,0.0484,0.0191
54,5,cf_3,,1,,3,,,27.9904,3,,0.1161,4,False,0.0484,0.1404
55,5,cf_4,1,,,,,,28.0102,7,,0.3125,3,True,0.0484,0.0079
56,5,cf_5,,,,1,1,,28.0102,,,0.2708,3,True,0.0484,0.0211
57,5,cf_6,,3,3,7,2,,27.9904,,,0.3125,5,False,0.0484,0.1127
58,5,cf_7,,3,4,,3,,27.9904,4,,0.2798,5,False,0.0484,0.0966
59,5,cf_8,,3,4,7,,,27.9904,5,,0.3601,5,False,0.0484,0.092
60,5,cf_9,3,4,,7,1,,27.9904,,,0.375,5,False,0.0484,0.0949
61,5,cf_10,,3,4,6,1,,27.9904,,,0.375,5,False,0.0484,0.1971
62,6,xin,2,3,5,4,1,0,27.6817,4,0.98,,,,0.0539,
63,6,cf_1,,,,,,,27.6817,,,0.0682,1,False,0.0539,0.1166
64,6,cf_2,3,,,,,,27.6817,6,,0.1664,3,False,0.0539,0.0856
65,6,cf_3,,,6,,,,27.6817,5,,0.111,3,False,0.0539,0.0963
66,6,cf_4,,,1,,,,27.6817,1,,0.2217,3,False,0.0539,0.0673
67,6,cf_5,,,,1,,,27.6817,0,,0.2021,3,False,0.0539,0.1786
68,6,cf_6,,,,7,,,27.6817,7,,0.1842,3,False,0.0539,0.1515
69,6,cf_7,,,,,4,,27.6817,2,,0.2289,3,False,0.0539,0.0559
70,6,cf_8,,2,,,,,27.6817,3,,0.1277,3,False,0.0539,0.0406
71,6,cf_9,,,4,,2,,27.6817,5,,0.1527,4,False,0.0539,0.1822
72,6,cf_10,1,5,4,,,,27.6817,,,0.239,4,False,0.0539,0.0293
73,7,xin,2,3,6,3,1,0,20.4382,2,1.16,,,,0.0565,
74,7,cf_1,,,,,,,20.4382,,,0.0001,1,False,0.0565,0.0565
75,7,cf_2,,,,2,,,20.4382,4,,0.0813,3,False,0.0565,0.0297
76,7,cf_3,,,1,,2,,20.4382,,,0.2501,3,True,0.0565,0.0179
77,7,cf_4,,,,4,,,20.4491,,,0.1562,2,False,0.0565,0.1464
78,7,cf_5,,,5,2,,,20.4382,5,,0.1313,4,True,0.0565,0.0071
79,7,cf_6,1,1,,,,,20.4382,5,,0.3251,4,True,0.0565,0.0092
80,7,cf_7,,,,5,2,,20.4382,7,,0.3126,4,False,0.0565,0.0655
81,7,cf_8,,,,2,2,,20.4382,5,,0.2313,4,False,0.0565,0.0306
82,7,cf_9,,1,,6,,,20.4382,3,,0.2438,4,False,0.0565,0.0685
83,7,cf_10,,1,,6,,,20.4382,7,,0.3438,4,False,0.0565,0.0565
84,8,xin,6,4,1,1,1,0,26.0146,0,1.17,,,,0.1216,
85,8,cf_1,,,,,,,26.0146,,,0.0,1,False,0.1216,0.1216
86,8,cf_2,1,,,3,,,26.0146,3,,0.2286,4,True,0.1216,0.0392
87,8,cf_3,3,5,,,,,26.0146,7,,0.225,4,False,0.1216,0.1349
88,8,cf_4,3,6,,,,,26.0146,5,,0.2143,4,True,0.1216,0.0249
89,8,cf_5,3,1,,3,,,26.0146,,,0.2,4,True,0.1216,0.0146
90,8,cf_6,4,,4,4,,,26.0146,,,0.2,4,False,0.1216,0.132
91,8,cf_7,4,,,6,,,26.023,,,0.3,3,False,0.1216,0.0923
92,8,cf_8,1,3,6,5,,,26.0146,,,0.375,5,True,0.1216,0.0596
93,8,cf_9,3,3,2,5,,,26.0146,,,0.225,5,True,0.1216,0.0543
94,8,cf_10,5,1,5,,,,26.0146,4,,0.2715,5,False,0.1216,0.0711

In [9]:
from cf_bench.utils import select_one_cf_per_query

# Select one CF per observation
# prefers valid CFs without violations, and lowest Gower
single_gower_df = select_one_cf_per_query(batch_df, selector="gower")
single_gower_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,1.22,,,,0.026,
9,0,cf_1,,,,,,,18.9866,,,0.0,1,True,0.026,0.0123
1,1,xin,3,4,1,2,3,0,22.3757,0,1.3,,,,0.2497,
10,1,cf_2,,,,,1,,22.3757,,,0.0833,2,True,0.2497,0.07
2,2,xin,5,3,1,1,4,0,22.694,7,1.08,,,,0.218,
11,2,cf_7,,,2,2,1,,22.68,,,0.267,4,True,0.218,0.0124
3,3,xin,3,3,6,6,2,0,24.3418,1,1.18,,,,0.0653,
12,3,cf_1,,,,,,,24.3418,,,0.0001,1,False,0.0653,0.0653
4,4,xin,5,4,2,7,1,0,21.2585,3,1.31,,,,0.0811,
13,4,cf_1,,,,,,,21.2585,,,0.1118,1,True,0.0811,0.0141
5,5,xin,2,2,1,2,4,0,27.9904,0,1.19,,,,0.0484,
14,5,cf_2,,,,3,,,27.9904,6,,0.128,3,True,0.0484,0.0191
6,6,xin,2,3,5,4,1,0,27.6817,4,0.98,,,,0.0539,
15,6,cf_1,,,,,,,27.6817,,,0.0682,1,False,0.0539,0.1166
7,7,xin,2,3,6,3,1,0,20.4382,2,1.16,,,,0.0565,
16,7,cf_5,,,5,2,,,20.4382,5,,0.1313,4,True,0.0565,0.0071
8,8,xin,6,4,1,1,1,0,26.0146,0,1.17,,,,0.1216,
17,8,cf_5,3,1,,3,,,26.0146,,,0.2,4,True,0.1216,0.0146

In [10]:
# Random selection (Gower may pick only BMI variations)
single_random_df = select_one_cf_per_query(batch_df, selector="random")
single_random_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,1.22,,,,0.026,
9,0,cf_2,,1,5,,1,,18.9866,,,0.2917,4,True,0.026,0.0026
1,1,xin,3,4,1,2,3,0,22.3757,0,1.3,,,,0.2497,
10,1,cf_2,,,,,1,,22.3757,,,0.0833,2,True,0.2497,0.07
2,2,xin,5,3,1,1,4,0,22.694,7,1.08,,,,0.218,
11,2,cf_3,1,,,,2,,22.6757,,,0.3333,3,True,0.218,0.0662
3,3,xin,3,3,6,6,2,0,24.3418,1,1.18,,,,0.0653,
12,3,cf_1,,,,,,,24.3418,,,0.0001,1,False,0.0653,0.0653
4,4,xin,5,4,2,7,1,0,21.2585,3,1.31,,,,0.0811,
13,4,cf_2,,2,5,,,,21.2585,,,0.3618,3,True,0.0811,0.0091
5,5,xin,2,2,1,2,4,0,27.9904,0,1.19,,,,0.0484,
14,5,cf_2,,,,3,,,27.9904,6,,0.128,3,True,0.0484,0.0191
6,6,xin,2,3,5,4,1,0,27.6817,4,0.98,,,,0.0539,
15,6,cf_1,,,,,,,27.6817,,,0.0682,1,False,0.0539,0.1166
7,7,xin,2,3,6,3,1,0,20.4382,2,1.16,,,,0.0565,
16,7,cf_3,,,1,,2,,20.4382,,,0.2501,3,True,0.0565,0.0179
8,8,xin,6,4,1,1,1,0,26.0146,0,1.17,,,,0.1216,
17,8,cf_4,3,6,,,,,26.0146,5,,0.2143,4,True,0.1216,0.0249