In [1]:
import os
from pathlib import Path

import numpy as np
import pandas as pd

from dotenv import load_dotenv

load_dotenv()

CF_OUTPUTS = Path(os.getenv("CF_OUTPUTS"))
print(CF_OUTPUTS)
print(CF_OUTPUTS.is_dir())

/home/dyretna/Dokument/Code/GitHub/nightingale_projects/cf_bench/cf_outputs
True

In [2]:
GEN_1_GENETIC = CF_OUTPUTS / "gen1_models_explainers_constraints" / "genetic_exp"
GEN_1_GENETIC.is_dir()

True

In [3]:
batch_data = GEN_1_GENETIC / "RF_prange_highthres_2026-04-29" / "annotated.csv"
batch_df = pd.read_csv(batch_data)

### set PD options

In [4]:
pd.set_option("display.max_rows", None)

In [5]:
# dtypes
int_columns = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "dosprt", "hltprhc", "Nchanged"]
float_columns = ["bmi", "gower_distance", "risk_before", "predicted_risk_after", "cf_gen_time_sec"]


# Convert and fill NaN with empty strings
batch_df[int_columns] = batch_df[int_columns].astype("Int64").astype("string").fillna("")
batch_df[float_columns] = batch_df[float_columns].round(4).astype("string").fillna("")
batch_df["valid"] = batch_df["valid"].astype("string").fillna("")

In [6]:
batch_df = batch_df.drop(columns=["hltprhc", "target_risk"])
batch_df["cf_id"] = batch_df["cf_id"].replace({"original": "xin"})

In [7]:
# correct_cf_idx
# Fix cf_id indexing - group by query_index and number counterfactuals sequentially
def fix_cf_id(df):
    # For each query_index group
    fixed_rows = []
    for query_idx, group in df.groupby('query_index', sort=False):
        group = group.copy()
        # First row is xin (original)
        xin_mask = group['cf_id'] == 'xin'
        cf_mask = ~xin_mask

        # Keep xin rows as is
        xin_rows = group[xin_mask].copy()

        # Fix cf rows
        cf_rows = group[cf_mask].copy()
        if len(cf_rows) > 0:
            # Number them cf_1, cf_2, cf_3, etc.
            cf_rows['cf_id'] = [f'cf_{i+1}' for i in range(len(cf_rows))]

        # Combine back
        fixed_rows.append(xin_rows)
        if len(cf_rows) > 0:
            fixed_rows.append(cf_rows)

    return pd.concat(fixed_rows, ignore_index=True)

In [8]:
batch_df = fix_cf_id(batch_df)
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,2.0,,,,0.0633,
1,0,cf_1,,,,,,,16.7168,,,0.1056,1,False,0.0633,0.0733
2,0,cf_2,,,,,,,16.389,,,0.1208,1,False,0.0633,0.11
3,0,cf_3,,,,7,,,18.9745,,,0.1256,2,False,0.0633,0.07
4,0,cf_4,,,,6,,,18.268,,,0.1168,2,False,0.0633,0.2067
5,0,cf_5,3,,,,,,17.7696,,,0.1191,2,False,0.0633,0.0667
6,0,cf_6,,,,7,,,17.2426,,,0.2061,2,False,0.0633,0.09
7,0,cf_7,,,,,,,16.8547,5,,0.1885,2,False,0.0633,0.1033
8,0,cf_8,3,,,,,,16.389,,,0.1833,2,False,0.0633,0.1267
9,0,cf_9,2,,,,,,16.2995,,,0.25,2,False,0.0633,0.1733
10,0,cf_10,,,,7,,,18.9745,7,,0.2506,3,True,0.0633,0.03
11,1,xin,3,4,1,2,3,0,22.3757,0,2.1,,,,0.1467,
12,1,cf_1,,,,,,,22.3757,,,0.0046,1,False,0.1467,0.1467
13,1,cf_2,,,4,,,,22.3757,4,,0.2011,3,False,0.1467,0.13
14,1,cf_3,,,2,,1,,22.3757,,,0.1713,3,True,0.1467,0.0233
15,1,cf_4,1,,,4,,,22.3757,,,0.1796,3,False,0.1467,0.09
16,1,cf_5,2,,,,1,,22.3757,,,0.1921,3,True,0.1467,0.01
17,1,cf_6,,,,7,,,22.3757,7,,0.2546,3,False,0.1467,0.0767
18,1,cf_7,,,,3,1,,22.3757,,,0.1546,3,True,0.1467,0.0
19,1,cf_8,,,,,2,,22.3757,7,,0.1921,3,False,0.1467,0.09
20,1,cf_9,,,,,1,,22.3757,1,,0.1475,3,True,0.1467,0.05
21,1,cf_10,,3,,,,,22.3757,6,,0.2368,3,False,0.1467,0.1667
22,2,xin,5,3,1,1,4,0,22.694,7,2.13,,,,0.1567,
23,2,cf_1,3,,,,2,,22.68,,,0.1669,3,True,0.1567,0.0133
24,2,cf_2,,,,7,2,,22.6757,,,0.2087,3,False,0.1567,0.1639
25,2,cf_3,,,,6,1,,22.6757,,,0.2295,3,True,0.1567,0.0633
26,2,cf_4,,,,4,2,,22.6757,,,0.1462,3,True,0.1567,0.0633
27,2,cf_5,,,,3,2,,22.6757,,,0.1253,3,False,0.1567,0.0867
28,2,cf_6,,,,,,,15.6999,,,0.125,1,False,0.1567,0.2033
29,2,cf_7,2,,6,7,,,22.68,,,0.3753,4,False,0.1567,0.24
30,2,cf_8,,,3,4,1,,22.68,,,0.2378,4,True,0.1567,0.0233
31,2,cf_9,,,2,6,1,,22.68,,,0.2544,4,True,0.1567,0.01
32,3,xin,3,3,6,6,2,0,24.3418,1,2.21,,,,0.02,
33,3,cf_1,,,,,,,24.3375,,,0.0002,1,True,0.02,0.01
34,3,cf_2,,,,7,,,24.3375,,,0.1252,2,False,0.02,0.0333
35,3,cf_3,,,,,,,24.3375,5,,0.1002,2,False,0.02,0.2333
36,3,cf_4,,,,,,,24.3375,4,,0.0752,2,False,0.02,0.02
37,3,cf_5,,,,,,,24.3375,3,,0.0502,2,True,0.02,0.0
38,3,cf_6,2,,,,,,24.3375,,,0.1252,2,False,0.02,0.1233
39,3,cf_7,,,,,,,21.3023,,,0.125,1,False,0.02,0.0133
40,3,cf_8,,,,,,,23.8382,6,,0.1457,2,False,0.02,0.1367
41,4,xin,5,4,2,7,1,0,21.2585,3,2.29,,,,0.0267,
42,4,cf_1,,,,,,,21.2585,,,0.1118,1,False,0.0267,0.0267
43,4,cf_2,,,6,,,,21.2585,,,0.2368,2,True,0.0267,0.0033
44,4,cf_3,,,3,,,,21.2585,,,0.1431,2,True,0.0267,0.01
45,4,cf_4,,3,,,,,21.2585,,,0.1535,2,True,0.0267,0.0133
46,4,cf_5,,,5,,,,21.2585,,,0.2056,2,True,0.0267,0.0067
47,4,cf_6,4,,,,,,21.2585,,,0.1431,2,False,0.0267,0.03
48,4,cf_7,3,,,,,,21.2585,,,0.1743,2,False,0.0267,0.0533
49,4,cf_8,1,,6,,,,21.2585,,,0.3618,3,False,0.0267,0.0167
50,4,cf_9,2,1,,,,,21.2585,,,0.3306,3,False,0.0267,0.05
51,4,cf_10,2,2,,,,,21.2585,,,0.2889,3,False,0.0267,0.0433
52,5,xin,2,2,1,2,4,0,27.9904,0,2.12,,,,0.3267,
53,5,cf_1,,,,,1,,27.9904,,,0.3357,2,True,0.3267,0.0833
54,5,cf_2,,,,7,1,,27.9904,,,0.4607,3,True,0.3267,0.04
55,5,cf_3,,,,6,1,,27.9904,,,0.4357,3,True,0.3267,0.12
56,5,cf_4,,,,4,1,,27.9904,,,0.3857,3,True,0.3267,0.0433
57,5,cf_5,,,,,2,,27.9904,2,,0.3565,3,True,0.3267,0.0333
58,5,cf_6,1,,,,3,,27.9904,,,0.3773,3,True,0.3267,0.0667
59,5,cf_7,1,,,,,,27.9904,4,,0.4607,3,True,0.3267,0.0833
60,6,xin,2,3,5,4,1,0,27.6817,4,1.98,,,,0.1467,
61,6,cf_1,,,,,,,27.3286,,,0.0097,1,False,0.1467,0.1267
62,6,cf_2,,,,,,,25.5938,,,0.0572,1,True,0.1467,0.0667
63,6,cf_3,,,,,,,24.7544,,,0.0802,1,True,0.1467,0.0533
64,6,cf_4,,,,,,,24.4414,,,0.0888,1,False,0.1467,0.1833
65,6,cf_5,,,,7,,,27.1944,,,0.1384,2,True,0.1467,0.0367
66,6,cf_6,,,,,,,27.0086,7,,0.1434,2,True,0.1467,0.0233
67,6,cf_7,,,,,,,26.7673,7,,0.1501,2,True,0.1467,0.0067
68,6,cf_8,,,,,,,26.7588,6,,0.1086,2,True,0.1467,0.04
69,6,cf_9,,,,,,,23.471,,,0.1154,1,True,0.1467,0.0067
70,6,cf_10,,,,,,,23.1195,,,0.125,1,True,0.1467,0.0033
71,7,xin,2,3,6,3,1,0,20.4382,2,1.97,,,,0.0133,
72,7,cf_1,,,,,,,20.4284,,,0.0006,1,False,0.0133,0.02
73,7,cf_2,,,,,,,20.0717,,,0.0238,1,False,0.0133,0.01
74,7,cf_3,,,,,,,19.907,,,0.0345,1,False,0.0133,0.01
75,7,cf_4,,,,,,,19.467,,,0.0631,1,True,0.0133,0.0
76,7,cf_5,,,,,,,19.0594,,,0.0895,1,True,0.0133,0.0
77,7,cf_6,,,,,,,18.5129,,,0.125,1,False,0.0133,0.01
78,7,cf_7,,,,7,,,20.4294,,,0.1256,2,False,0.0133,0.01
79,7,cf_8,,,,6,,,20.4284,,,0.0944,2,False,0.0133,0.0333
80,7,cf_9,,,,,,,20.4284,5,,0.1256,2,False,0.0133,0.01
81,7,cf_10,,,,4,,,20.4284,,,0.0319,2,False,0.0133,0.0617
82,8,xin,6,4,1,1,1,0,26.0146,0,2.03,,,,0.09,
83,8,cf_1,,,6,7,,,26.0044,,,0.2508,3,False,0.09,0.18
84,8,cf_2,3,,,5,,,26.0044,,,0.1591,3,True,0.09,0.0367
85,8,cf_3,2,,,,,,26.0044,3,,0.1543,3,False,0.09,0.0633
86,8,cf_4,1,,,4,,,24.366,,,0.3125,3,False,0.09,0.0867
87,8,cf_5,1,1,,,,,24.366,,,0.375,3,True,0.09,0.0367
88,8,cf_6,2,3,6,,,,26.0044,,,0.2674,4,True,0.09,0.02
89,8,cf_7,2,3,,7,,,26.0044,,,0.2674,4,True,0.09,0.0033
90,8,cf_8,1,2,,2,,,26.0044,,,0.2299,4,False,0.09,0.1267
91,8,cf_9,3,2,,,,,26.0044,7,,0.2841,4,True,0.09,0.0067

In [9]:
from cf_bench.utils import select_one_cf_per_query

# Select one CF per observation
# prefers valid CFs without violations, and lowest Gower
single_gower_df = select_one_cf_per_query(batch_df, selector="gower")
single_gower_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,2.0,,,,0.0633,
9,0,cf_10,,,,7,,,18.9745,7,,0.2506,3,True,0.0633,0.03
1,1,xin,3,4,1,2,3,0,22.3757,0,2.1,,,,0.1467,
10,1,cf_9,,,,,1,,22.3757,1,,0.1475,3,True,0.1467,0.05
2,2,xin,5,3,1,1,4,0,22.694,7,2.13,,,,0.1567,
11,2,cf_4,,,,4,2,,22.6757,,,0.1462,3,True,0.1567,0.0633
3,3,xin,3,3,6,6,2,0,24.3418,1,2.21,,,,0.02,
12,3,cf_1,,,,,,,24.3375,,,0.0002,1,True,0.02,0.01
4,4,xin,5,4,2,7,1,0,21.2585,3,2.29,,,,0.0267,
13,4,cf_3,,,3,,,,21.2585,,,0.1431,2,True,0.0267,0.01
5,5,xin,2,2,1,2,4,0,27.9904,0,2.12,,,,0.3267,
14,5,cf_1,,,,,1,,27.9904,,,0.3357,2,True,0.3267,0.0833
6,6,xin,2,3,5,4,1,0,27.6817,4,1.98,,,,0.1467,
15,6,cf_2,,,,,,,25.5938,,,0.0572,1,True,0.1467,0.0667
7,7,xin,2,3,6,3,1,0,20.4382,2,1.97,,,,0.0133,
16,7,cf_4,,,,,,,19.467,,,0.0631,1,True,0.0133,0.0
8,8,xin,6,4,1,1,1,0,26.0146,0,2.03,,,,0.09,
17,8,cf_2,3,,,5,,,26.0044,,,0.1591,3,True,0.09,0.0367

In [10]:
# Random selection (Gower may pick only BMI variations)
single_random_df = select_one_cf_per_query(batch_df, selector="random")
single_random_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,2.0,,,,0.0633,
9,0,cf_10,,,,7,,,18.9745,7,,0.2506,3,True,0.0633,0.03
1,1,xin,3,4,1,2,3,0,22.3757,0,2.1,,,,0.1467,
10,1,cf_5,2,,,,1,,22.3757,,,0.1921,3,True,0.1467,0.01
2,2,xin,5,3,1,1,4,0,22.694,7,2.13,,,,0.1567,
11,2,cf_3,,,,6,1,,22.6757,,,0.2295,3,True,0.1567,0.0633
3,3,xin,3,3,6,6,2,0,24.3418,1,2.21,,,,0.02,
12,3,cf_5,,,,,,,24.3375,3,,0.0502,2,True,0.02,0.0
4,4,xin,5,4,2,7,1,0,21.2585,3,2.29,,,,0.0267,
13,4,cf_3,,,3,,,,21.2585,,,0.1431,2,True,0.0267,0.01
5,5,xin,2,2,1,2,4,0,27.9904,0,2.12,,,,0.3267,
14,5,cf_1,,,,,1,,27.9904,,,0.3357,2,True,0.3267,0.0833
6,6,xin,2,3,5,4,1,0,27.6817,4,1.98,,,,0.1467,
15,6,cf_3,,,,,,,24.7544,,,0.0802,1,True,0.1467,0.0533
7,7,xin,2,3,6,3,1,0,20.4382,2,1.97,,,,0.0133,
16,7,cf_5,,,,,,,19.0594,,,0.0895,1,True,0.0133,0.0
8,8,xin,6,4,1,1,1,0,26.0146,0,2.03,,,,0.09,
17,8,cf_5,1,1,,,,,24.366,,,0.375,3,True,0.09,0.0367