### imports and pandas settings

In [1]:
import os
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv

In [2]:
pd.set_option("display.max_rows", None)

### set the path to data file

In [3]:
load_dotenv()

CF_OUTPUTS = Path(os.getenv("CF_OUTPUTS"))
print(CF_OUTPUTS)
print(CF_OUTPUTS.is_dir())

/home/dyretna/Dokument/Code/GitHub/nightingale_projects/cf_bench/cf_outputs
True

In [4]:
batch_data = CF_OUTPUTS / "predictors_vs_threshold" / "xgb_optimized" / "XGBoost_thres0.5_2026-05-11" / "annotated.csv"

### load data 
convert to string to fillna with whitespace
we drop:  
- target_risk (half of "risk_before") , and 
- "hltprhc"

we rename "original" in df_id to "xin" (HL standards)

In [5]:
# Load CSV
batch_df = pd.read_csv(batch_data)

In [6]:
# Feature columns
feature_cols = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "bmi", "dosprt"]

# dtypes
int_columns = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "dosprt", "hltprhc", "Nchanged"]
float_columns = ["bmi", "gower_distance", "risk_before", "predicted_risk_after", "cf_gen_time_sec"]


# Convert and fill NaN with empty strings
batch_df[int_columns] = batch_df[int_columns].astype("Int64").astype("string").fillna("")
batch_df[float_columns] = batch_df[float_columns].round(4).astype("string").fillna("")
batch_df["valid"] = batch_df["valid"].astype("string").fillna("")

In [7]:
batch_df = batch_df.drop(columns=["hltprhc", "target_risk"])
batch_df["cf_id"] = batch_df["cf_id"].replace({"original": "xin"})

### All CFs

In [8]:
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,1.09,,,,,
1,0,cf_1,,,,,,,18.8688,,,0.0062,1,False,0.0743,0.0754
2,0,cf_2,,,,7,,,18.9745,,,0.1256,2,False,0.0743,0.0972
3,0,cf_3,2,,,,,,18.5952,,,0.1457,2,False,0.0743,0.1116
4,0,cf_4,,,,,,,17.5549,5,,0.165,2,True,0.0743,0.0099
5,0,cf_5,,,,6,,,17.4866,,,0.1627,2,False,0.0743,0.1366
6,0,cf_6,,,,6,,,17.0861,,,0.1839,2,False,0.0743,0.1366
7,0,cf_7,3,,,,,,16.7475,,,0.1809,2,False,0.0743,0.1413
8,0,cf_8,,,,7,,,16.6236,,,0.25,2,False,0.0743,0.1364
9,0,cf_9,,,,7,,,18.9745,7,,0.2506,3,True,0.0743,0.0051
10,0,cf_10,,,6,7,,,18.9745,,,0.2506,3,False,0.0743,0.1623
11,1,xin,3,4,1,2,3,0,22.3757,0,1.15,,,,,
12,1,cf_1,,,,,,,22.3757,,,0.0046,1,False,0.0484,0.0484
13,1,cf_2,,,2,,1,,22.3757,,,0.2546,3,False,0.0484,0.0534
14,1,cf_3,,,,3,1,,22.3757,,,0.1546,3,False,0.0484,0.0256
15,1,cf_4,,,,,1,,22.3757,1,,0.1475,3,False,0.0484,0.0503
16,1,cf_5,,3,,,,,22.3757,6,,0.1534,3,False,0.0484,0.0552
17,1,cf_6,2,,,,1,,22.3757,,,0.2546,3,True,0.0484,0.0105
18,1,cf_7,,,,7,,,22.3757,7,,0.2546,3,False,0.0484,0.4315
19,1,cf_8,,2,2,,,,22.3757,4,,0.2844,4,True,0.0484,0.0052
20,1,cf_9,,1,,,2,,22.3757,3,,0.2457,4,False,0.0484,0.0278
21,1,cf_10,,1,,,1,,22.3757,5,,0.3439,4,True,0.0484,0.0061
22,2,xin,5,3,1,1,4,0,22.694,7,1.13,,,,,
23,2,cf_1,3,,,,2,,22.68,,,0.1461,3,False,0.0647,0.0569
24,2,cf_2,3,,,,3,,22.68,,,0.1044,3,True,0.0647,0.0084
25,2,cf_3,,,,6,1,,22.6757,,,0.2295,3,False,0.0647,0.0406
26,2,cf_4,,,,3,2,,22.6757,,,0.1254,3,True,0.0647,0.0185
27,2,cf_5,2,,,,3,,22.6757,,,0.1358,3,True,0.0647,0.0131
28,2,cf_6,3,,,,2,,22.6757,,,0.1462,3,False,0.0647,0.0569
29,2,cf_7,,,,,,,16.2948,,,0.125,1,False,0.0647,0.0994
30,2,cf_8,1,,,4,,,21.0,,,0.2206,3,True,0.0647,0.0254
31,2,cf_9,2,,,7,1,,22.68,,,0.344,4,False,0.0647,0.0336
32,2,cf_10,,,6,2,3,,22.68,,,0.1878,4,False,0.0647,0.0801
33,3,xin,3,3,6,6,2,0,24.3418,1,1.23,,,,,
34,3,cf_1,,,,,,,24.3375,,,0.0006,1,False,0.0048,0.0048
35,3,cf_2,,,,7,,,24.3375,,,0.1256,2,False,0.0048,0.0447
36,3,cf_3,,,,,,,24.3375,5,,0.0839,2,False,0.0048,0.3142
37,3,cf_4,,,,,,,24.3375,4,,0.0631,2,False,0.0048,0.0342
38,3,cf_5,,,,,,,24.3375,3,,0.0423,2,False,0.0048,0.0071
39,3,cf_6,,,,,1,,24.3375,,,0.1256,2,False,0.0048,0.0111
40,3,cf_7,,2,,,,,24.3375,,,0.1256,2,False,0.0048,0.0031
41,3,cf_8,,,,,,,24.3375,7,,0.1256,2,False,0.0048,0.4341
42,3,cf_9,,,,,,,24.0,3,,0.0907,2,False,0.0048,0.0267
43,3,cf_10,,,,,,,23.4697,3,,0.1667,2,False,0.0048,0.0519
44,4,xin,5,4,2,7,1,0,21.2585,3,1.26,,,,,
45,4,cf_1,,,,,,,21.2585,,,0.0,1,False,0.0259,0.0295
46,4,cf_2,,,6,,,,21.2585,,,0.125,2,False,0.0259,0.015
47,4,cf_3,,,3,,,,21.2585,,,0.0313,2,False,0.0259,0.0132
48,4,cf_4,,,4,,,,21.2585,,,0.0625,2,False,0.0259,0.0185
49,4,cf_5,,3,,,,,21.2585,,,0.125,2,False,0.0259,0.0409
50,4,cf_6,4,,,,,,21.2585,,,0.0313,2,True,0.0259,0.007
51,4,cf_7,3,,,,,,21.2585,,,0.0625,2,True,0.0259,0.0118
52,4,cf_8,1,,,,,,21.2585,,,0.125,2,False,0.0259,0.0178
53,4,cf_9,,,,,,,20.0,,,0.125,1,False,0.0259,0.033
54,4,cf_10,1,,4,,,,21.2585,,,0.1875,3,False,0.0259,0.0527
55,5,xin,2,2,1,2,4,0,27.9904,0,1.16,,,,,
56,5,cf_1,,,,,,,27.9904,,,0.2107,1,False,0.0272,0.0272
57,5,cf_2,,,4,,,,27.9904,,,0.3357,2,False,0.0272,0.0506
58,5,cf_3,,,,,3,,27.9904,,,0.2523,2,False,0.0272,0.0139
59,5,cf_4,,,,,1,,27.9904,,,0.3357,2,False,0.0272,0.019
60,5,cf_5,,,,5,1,,27.9904,,,0.4107,3,False,0.0272,0.0425
61,5,cf_6,,,,4,1,,27.9904,,,0.3857,3,False,0.0272,0.1024
62,5,cf_7,,,,7,1,,27.9904,,,0.4607,3,False,0.0272,0.1124
63,5,cf_8,,,,7,,,27.9904,2,,0.4607,3,False,0.0272,0.0406
64,5,cf_9,,,4,,1,,27.9904,,,0.4607,3,False,0.0272,0.1515
65,5,cf_10,,,,5,3,,27.9904,,,0.3273,3,True,0.0272,0.0104
66,6,xin,2,3,5,4,1,0,27.6817,4,1.09,,,,,
67,6,cf_1,,,,,,,27.4648,,,0.0078,1,False,0.0152,0.0132
68,6,cf_2,,,,,,,26.4312,,,0.045,1,False,0.0152,0.1606
69,6,cf_3,,,,,,,25.74,,,0.0698,1,False,0.0152,0.0303
70,6,cf_4,,,,,,,25.1281,,,0.0918,1,False,0.0152,0.0244
71,6,cf_5,,,,,,,27.6476,7,,0.1262,2,False,0.0152,0.0128
72,6,cf_6,,,,,,,24.404,,,0.1178,1,False,0.0152,0.0386
73,6,cf_7,,,,,,,27.2307,7,,0.1412,2,True,0.0152,0.0007
74,6,cf_8,,,,,,,24.2045,,,0.125,1,False,0.0152,0.0197
75,6,cf_9,,,,,,,26.9473,5,,0.0681,2,True,0.0152,0.0029
76,6,cf_10,1,,,,,,26.7376,,,0.1589,2,False,0.0152,0.1164
77,7,xin,2,3,6,3,1,0,20.4382,2,1.05,,,,,
78,7,cf_1,,,,,,,20.4284,,,0.0004,1,False,0.2012,0.1487
79,7,cf_2,,,,,,,20.2939,,,0.0061,1,False,0.2012,0.1262
80,7,cf_3,,,,,,,19.4902,,,0.0401,1,True,0.2012,0.0231
81,7,cf_4,,,,,,,19.1803,,,0.0532,1,True,0.2012,0.0092
82,7,cf_5,,,,,,,18.5891,,,0.0783,1,True,0.2012,0.0094
83,7,cf_6,,,,,,,18.4828,,,0.0828,1,True,0.2012,0.007
84,7,cf_7,,,,,,,17.9196,,,0.1066,1,True,0.2012,0.0056
85,7,cf_8,,,,,,,17.4847,,,0.125,1,True,0.2012,0.0056
86,7,cf_9,,,,7,,,20.4294,,,0.1254,2,True,0.2012,0.0322
87,7,cf_10,,,,4,,,20.4284,,,0.0317,2,False,0.2012,0.3256
88,8,xin,6,4,1,1,1,0,26.0146,0,1.16,,,,,
89,8,cf_1,,,,,,,22.0152,,,0.0916,1,True,0.1068,0.0226
90,8,cf_2,3,,,5,,,26.0044,,,0.1586,3,False,0.1068,0.0611
91,8,cf_3,4,,,2,,,26.0044,3,,0.1648,4,True,0.1068,0.0086
92,8,cf_4,2,,,7,,,26.0044,3,,0.319,4,True,0.1068,0.0283
93,8,cf_5,1,,6,,,,26.0044,3,,0.344,4,True,0.1068,0.0358
94,8,cf_6,,,,7,,,22.686,4,,0.3262,3,True,0.1068,0.0003
95,8,cf_7,4,3,,,,,25.378,1,,0.1375,4,False,0.1068,0.1396
96,8,cf_8,5,1,,,,,25.3737,2,,0.2272,4,True,0.1068,0.0438
97,8,cf_9,1,1,,,,,20.8863,,,0.3675,3,False,0.1068,0.1073
98,8,cf_10,,,,3,,,20.5568,4,,0.2917,3,True,0.1068,0.0052

### Filtering Valid CFs

In [9]:
from cf_bench.utils import filter_valid_cfs

batch_df = filter_valid_cfs(batch_df)
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,1.09,,,,,
9,0,cf_4,,,,,,,17.5549,5,,0.165,2,True,0.0743,0.0099
10,0,cf_9,,,,7,,,18.9745,7,,0.2506,3,True,0.0743,0.0051
1,1,xin,3,4,1,2,3,0,22.3757,0,1.15,,,,,
11,1,cf_6,2,,,,1,,22.3757,,,0.2546,3,True,0.0484,0.0105
12,1,cf_8,,2,2,,,,22.3757,4,,0.2844,4,True,0.0484,0.0052
13,1,cf_10,,1,,,1,,22.3757,5,,0.3439,4,True,0.0484,0.0061
2,2,xin,5,3,1,1,4,0,22.694,7,1.13,,,,,
14,2,cf_2,3,,,,3,,22.68,,,0.1044,3,True,0.0647,0.0084
15,2,cf_4,,,,3,2,,22.6757,,,0.1254,3,True,0.0647,0.0185
16,2,cf_5,2,,,,3,,22.6757,,,0.1358,3,True,0.0647,0.0131
17,2,cf_8,1,,,4,,,21.0,,,0.2206,3,True,0.0647,0.0254
3,3,xin,3,3,6,6,2,0,24.3418,1,1.23,,,,,
37,3,cf_1,,,,,,,24.3375,,,0.0006,1,False,0.0048,0.0048
4,4,xin,5,4,2,7,1,0,21.2585,3,1.26,,,,,
18,4,cf_6,4,,,,,,21.2585,,,0.0313,2,True,0.0259,0.007
19,4,cf_7,3,,,,,,21.2585,,,0.0625,2,True,0.0259,0.0118
5,5,xin,2,2,1,2,4,0,27.9904,0,1.16,,,,,
20,5,cf_10,,,,5,3,,27.9904,,,0.3273,3,True,0.0272,0.0104
6,6,xin,2,3,5,4,1,0,27.6817,4,1.09,,,,,
21,6,cf_7,,,,,,,27.2307,7,,0.1412,2,True,0.0152,0.0007
22,6,cf_9,,,,,,,26.9473,5,,0.0681,2,True,0.0152,0.0029
7,7,xin,2,3,6,3,1,0,20.4382,2,1.05,,,,,
23,7,cf_3,,,,,,,19.4902,,,0.0401,1,True,0.2012,0.0231
24,7,cf_4,,,,,,,19.1803,,,0.0532,1,True,0.2012,0.0092
25,7,cf_5,,,,,,,18.5891,,,0.0783,1,True,0.2012,0.0094
26,7,cf_6,,,,,,,18.4828,,,0.0828,1,True,0.2012,0.007
27,7,cf_7,,,,,,,17.9196,,,0.1066,1,True,0.2012,0.0056
28,7,cf_8,,,,,,,17.4847,,,0.125,1,True,0.2012,0.0056
29,7,cf_9,,,,7,,,20.4294,,,0.1254,2,True,0.2012,0.0322
8,8,xin,6,4,1,1,1,0,26.0146,0,1.16,,,,,
30,8,cf_1,,,,,,,22.0152,,,0.0916,1,True,0.1068,0.0226
31,8,cf_3,4,,,2,,,26.0044,3,,0.1648,4,True,0.1068,0.0086
32,8,cf_4,2,,,7,,,26.0044,3,,0.319,4,True,0.1068,0.0283
33,8,cf_5,1,,6,,,,26.0044,3,,0.344,4,True,0.1068,0.0358
34,8,cf_6,,,,7,,,22.686,4,,0.3262,3,True,0.1068,0.0003
35,8,cf_8,5,1,,,,,25.3737,2,,0.2272,4,True,0.1068,0.0438
36,8,cf_10,,,,3,,,20.5568,4,,0.2917,3,True,0.1068,0.0052

### select one CF

In [10]:
from cf_bench.utils import select_one_cf_per_query

# Select one CF per observation (prefers valid CFs without violations)
single_cf_df = select_one_cf_per_query(batch_df, prefer_no_violations=True)
single_cf_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,1.09,,,,,
9,0,cf_9,,,,7,,,18.9745,7,,0.2506,3,True,0.0743,0.0051
1,1,xin,3,4,1,2,3,0,22.3757,0,1.15,,,,,
10,1,cf_6,2,,,,1,,22.3757,,,0.2546,3,True,0.0484,0.0105
2,2,xin,5,3,1,1,4,0,22.694,7,1.13,,,,,
11,2,cf_4,,,,3,2,,22.6757,,,0.1254,3,True,0.0647,0.0185
3,3,xin,3,3,6,6,2,0,24.3418,1,1.23,,,,,
12,3,cf_1,,,,,,,24.3375,,,0.0006,1,False,0.0048,0.0048
4,4,xin,5,4,2,7,1,0,21.2585,3,1.26,,,,,
13,4,cf_7,3,,,,,,21.2585,,,0.0625,2,True,0.0259,0.0118
5,5,xin,2,2,1,2,4,0,27.9904,0,1.16,,,,,
14,5,cf_10,,,,5,3,,27.9904,,,0.3273,3,True,0.0272,0.0104
6,6,xin,2,3,5,4,1,0,27.6817,4,1.09,,,,,
15,6,cf_9,,,,,,,26.9473,5,,0.0681,2,True,0.0152,0.0029
7,7,xin,2,3,6,3,1,0,20.4382,2,1.05,,,,,
16,7,cf_3,,,,,,,19.4902,,,0.0401,1,True,0.2012,0.0231
8,8,xin,6,4,1,1,1,0,26.0146,0,1.16,,,,,
17,8,cf_1,,,,,,,22.0152,,,0.0916,1,True,0.1068,0.0226

In [11]:
from cf_bench.dice_adapters import DiceRecommender

recommender = DiceRecommender()

# Format a single query
for idx in range(0, 10):
    print(recommender.format_query(batch_df, query_index=idx))

=== Query index '0' ===
Task / Target: hltprhc
Query instance index: 0

Original instance:
  etfruit: 4
  eatveg: 3
  cgtsmok: 3
  alcfreq: 4
  slprl: 2
  paccnois: 0
  bmi: 18.9866
  dosprt: 0


=== Counterfactuals ===

--- cf_4 ---
Predicted risk: 0.0099
Valid: True
Changes:
  bmi: 18.9866 → 17.5549
  dosprt: 0 → 5

--- cf_9 ---
Predicted risk: 0.0051
Valid: True
Changes:
  alcfreq: 4 → 7
  bmi: 18.9866 → 18.9745
  dosprt: 0 → 7


=== Query index '1' ===
Task / Target: hltprhc
Query instance index: 1

Original instance:
  etfruit: 3
  eatveg: 4
  cgtsmok: 1
  alcfreq: 2
  slprl: 3
  paccnois: 0
  bmi: 22.3757
  dosprt: 0


=== Counterfactuals ===

--- cf_6 ---
Predicted risk: 0.0105
Valid: True
Changes:
  etfruit: 3 → 2
  slprl: 3 → 1

--- cf_8 ---
Predicted risk: 0.0052
Valid: True
Changes:
  eatveg: 4 → 2
  cgtsmok: 1 → 2
  dosprt: 0 → 4

--- cf_10 ---
Predicted risk: 0.0061
Valid: True
Changes:
  eatveg: 4 → 1
  slprl: 3 → 1
  dosprt: 0 → 5


=== Query index '2' ===
Task / Target: hltprhc
Query instance index: 2

Original instance:
  etfruit: 5
  eatveg: 3
  cgtsmok: 1
  alcfreq: 1
  slprl: 4
  paccnois: 0
  bmi: 22.694
  dosprt: 7


=== Counterfactuals ===

--- cf_2 ---
Predicted risk: 0.0084
Valid: True
Changes:
  etfruit: 5 → 3
  slprl: 4 → 3
  bmi: 22.694 → 22.68

--- cf_4 ---
Predicted risk: 0.0185
Valid: True
Changes:
  alcfreq: 1 → 3
  slprl: 4 → 2
  bmi: 22.694 → 22.6757

--- cf_5 ---
Predicted risk: 0.0131
Valid: True
Changes:
  etfruit: 5 → 2
  slprl: 4 → 3
  bmi: 22.694 → 22.6757

--- cf_8 ---
Predicted risk: 0.0254
Valid: True
Changes:
  etfruit: 5 → 1
  alcfreq: 1 → 4
  bmi: 22.694 → 21.0


=== Query index '3' ===
Task / Target: hltprhc
Query instance index: 3

Original instance:
  etfruit: 3
  eatveg: 3
  cgtsmok: 6
  alcfreq: 6
  slprl: 2
  paccnois: 0
  bmi: 24.3418
  dosprt: 1


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.0048
Valid: False
Changes:
  bmi: 24.3418 → 24.3375


=== Query index '4' ===
Task / Target: hltprhc
Query instance index: 4

Original instance:
  etfruit: 5
  eatveg: 4
  cgtsmok: 2
  alcfreq: 7
  slprl: 1
  paccnois: 0
  bmi: 21.2585
  dosprt: 3


=== Counterfactuals ===

--- cf_6 ---
Predicted risk: 0.007
Valid: True
Changes:
  etfruit: 5 → 4

--- cf_7 ---
Predicted risk: 0.0118
Valid: True
Changes:
  etfruit: 5 → 3


=== Query index '5' ===
Task / Target: hltprhc
Query instance index: 5

Original instance:
  etfruit: 2
  eatveg: 2
  cgtsmok: 1
  alcfreq: 2
  slprl: 4
  paccnois: 0
  bmi: 27.9904
  dosprt: 0


=== Counterfactuals ===

--- cf_10 ---
Predicted risk: 0.0104
Valid: True
Changes:
  alcfreq: 2 → 5
  slprl: 4 → 3


=== Query index '6' ===
Task / Target: hltprhc
Query instance index: 6

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 5
  alcfreq: 4
  slprl: 1
  paccnois: 0
  bmi: 27.6817
  dosprt: 4


=== Counterfactuals ===

--- cf_7 ---
Predicted risk: 0.0007
Valid: True
Changes:
  bmi: 27.6817 → 27.2307
  dosprt: 4 → 7

--- cf_9 ---
Predicted risk: 0.0029
Valid: True
Changes:
  bmi: 27.6817 → 26.9473
  dosprt: 4 → 5


=== Query index '7' ===
Task / Target: hltprhc
Query instance index: 7

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 6
  alcfreq: 3
  slprl: 1
  paccnois: 0
  bmi: 20.4382
  dosprt: 2


=== Counterfactuals ===

--- cf_3 ---
Predicted risk: 0.0231
Valid: True
Changes:
  bmi: 20.4382 → 19.4902

--- cf_4 ---
Predicted risk: 0.0092
Valid: True
Changes:
  bmi: 20.4382 → 19.1803

--- cf_5 ---
Predicted risk: 0.0094
Valid: True
Changes:
  bmi: 20.4382 → 18.5891

--- cf_6 ---
Predicted risk: 0.007
Valid: True
Changes:
  bmi: 20.4382 → 18.4828

--- cf_7 ---
Predicted risk: 0.0056
Valid: True
Changes:
  bmi: 20.4382 → 17.9196

--- cf_8 ---
Predicted risk: 0.0056
Valid: True
Changes:
  bmi: 20.4382 → 17.4847

--- cf_9 ---
Predicted risk: 0.0322
Valid: True
Changes:
  alcfreq: 3 → 7
  bmi: 20.4382 → 20.4294


=== Query index '8' ===
Task / Target: hltprhc
Query instance index: 8

Original instance:
  etfruit: 6
  eatveg: 4
  cgtsmok: 1
  alcfreq: 1
  slprl: 1
  paccnois: 0
  bmi: 26.0146
  dosprt: 0


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.0226
Valid: True
Changes:
  bmi: 26.0146 → 22.0152

--- cf_3 ---
Predicted risk: 0.0086
Valid: True
Changes:
  etfruit: 6 → 4
  alcfreq: 1 → 2
  bmi: 26.0146 → 26.0044
  dosprt: 0 → 3

--- cf_4 ---
Predicted risk: 0.0283
Valid: True
Changes:
  etfruit: 6 → 2
  alcfreq: 1 → 7
  bmi: 26.0146 → 26.0044
  dosprt: 0 → 3

--- cf_5 ---
Predicted risk: 0.0358
Valid: True
Changes:
  etfruit: 6 → 1
  cgtsmok: 1 → 6
  bmi: 26.0146 → 26.0044
  dosprt: 0 → 3

--- cf_6 ---
Predicted risk: 0.0003
Valid: True
Changes:
  alcfreq: 1 → 7
  bmi: 26.0146 → 22.686
  dosprt: 0 → 4

--- cf_8 ---
Predicted risk: 0.0438
Valid: True
Changes:
  etfruit: 6 → 5
  eatveg: 4 → 1
  bmi: 26.0146 → 25.3737
  dosprt: 0 → 2

--- cf_10 ---
Predicted risk: 0.0052
Valid: True
Changes:
  alcfreq: 1 → 3
  bmi: 26.0146 → 20.5568
  dosprt: 0 → 4


=== Query index '9' ===
No recommendations available.