### imports and pandas settings

In [1]:
import os
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv

In [2]:
pd.set_option("display.max_rows", None)

### set the path to data file

In [3]:
load_dotenv()

CF_OUTPUTS = Path(os.getenv("CF_OUTPUTS"))
print(CF_OUTPUTS)
print(CF_OUTPUTS.is_dir())

/home/dyretna/Dokument/Code/GitHub/nightingale_projects/cf_bench/cf_outputs
True

In [4]:
batch_data = CF_OUTPUTS / "predictors_vs_threshold" / "xgb_optimized" / "XGBoost_thres0.9_2026-05-11" / "annotated.csv"

### load data 
convert to string to fillna with whitespace
we drop:  
- target_risk (half of "risk_before") , and 
- "hltprhc"

we rename "original" in df_id to "xin" (HL standards)

In [5]:
# Load CSV
batch_df = pd.read_csv(batch_data)

In [6]:
# Feature columns
feature_cols = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "bmi", "dosprt"]

# dtypes
int_columns = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "dosprt", "hltprhc", "Nchanged"]
float_columns = ["bmi", "gower_distance", "risk_before", "predicted_risk_after", "cf_gen_time_sec"]


# Convert and fill NaN with empty strings
batch_df[int_columns] = batch_df[int_columns].astype("Int64").astype("string").fillna("")
batch_df[float_columns] = batch_df[float_columns].round(4).astype("string").fillna("")
batch_df["valid"] = batch_df["valid"].astype("string").fillna("")

In [7]:
batch_df = batch_df.drop(columns=["hltprhc", "target_risk"])
batch_df["cf_id"] = batch_df["cf_id"].replace({"original": "xin"})

### All CFs

In [8]:
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,1.33,,,,,
1,0,cf_1,,,,,,,16.324,,,0.1109,1,False,0.0743,0.1184
2,0,cf_2,,,,7,,,18.9745,,,0.1255,2,False,0.0743,0.0972
3,0,cf_3,3,,,,,,18.8672,,,0.0466,2,False,0.0743,0.0904
4,0,cf_4,,,,6,,,18.7048,,,0.0951,2,False,0.0743,0.1265
5,0,cf_5,2,,,,,,17.982,,,0.1252,2,False,0.0743,0.1126
6,0,cf_6,,,6,,,,17.2216,,,0.1985,2,False,0.0743,0.044
7,0,cf_7,1,,,,,,17.2202,,,0.1986,2,False,0.0743,0.1948
8,0,cf_8,,,,,,,15.9856,5,,0.2143,2,True,0.0743,0.0099
9,0,cf_9,,,6,7,,,18.9745,,,0.2505,3,False,0.0743,0.1623
10,0,cf_10,,,,7,,,18.9745,7,,0.2505,3,True,0.0743,0.0051
11,1,xin,3,4,1,2,3,0,22.3757,0,1.24,,,,,
12,1,cf_1,,,,,,,22.3757,,,0.0046,1,False,0.0484,0.0484
13,1,cf_2,,,2,,1,,22.3757,,,0.2546,3,False,0.0484,0.0534
14,1,cf_3,,,,3,1,,22.3757,,,0.2546,3,False,0.0484,0.0256
15,1,cf_4,,,,,1,,22.3757,1,,0.1475,3,False,0.0484,0.0503
16,1,cf_5,,3,,,,,22.3757,6,,0.1743,3,False,0.0484,0.0552
17,1,cf_6,,3,,,1,,22.3757,,,0.1921,3,False,0.0484,0.1144
18,1,cf_7,2,,,,1,,22.3757,,,0.2546,3,True,0.0484,0.0105
19,1,cf_8,,2,2,,,,22.3757,7,,0.3796,4,True,0.0484,0.0137
20,1,cf_9,,2,,,1,,22.3757,7,,0.3796,4,False,0.0484,0.0877
21,2,xin,5,3,1,1,4,0,22.694,7,1.2,,,,,
22,2,cf_1,,,,,,,17.3764,,,0.125,1,False,0.0647,0.0994
23,2,cf_2,,,,3,2,,22.68,,,0.1337,3,True,0.0647,0.0185
24,2,cf_3,4,,,,2,,22.68,,,0.1149,3,False,0.0647,0.1316
25,2,cf_4,3,,,,2,,22.68,,,0.1462,3,False,0.0647,0.0569
26,2,cf_5,,,,6,1,,22.6757,,,0.2504,3,False,0.0647,0.0406
27,2,cf_6,2,,,5,,,22.6757,,,0.1942,3,False,0.0647,0.112
28,2,cf_7,,,2,,1,,22.6757,,,0.2504,3,True,0.0647,0.0079
29,2,cf_8,,,,3,2,,22.6757,,,0.1338,3,True,0.0647,0.0185
30,2,cf_9,1,2,,,,,22.6757,,,0.2504,3,True,0.0647,0.0031
31,2,cf_10,1,,,,2,,22.6757,,,0.2088,3,True,0.0647,0.0162
32,3,xin,3,3,6,6,2,0,24.3418,1,1.23,,,,,
33,3,cf_1,,,,,,,24.3375,,,0.0534,1,False,0.0048,0.0048
34,3,cf_2,,,,,,,24.3317,,,0.125,1,True,0.0048,0.0011
35,3,cf_3,,,,7,,,24.3375,,,0.1784,2,False,0.0048,0.0447
36,3,cf_4,,,,,,,24.3375,4,,0.1784,2,False,0.0048,0.0342
37,3,cf_5,,,,,,,24.3375,3,,0.1367,2,False,0.0048,0.0071
38,3,cf_6,,,,,1,,24.3375,,,0.1784,2,False,0.0048,0.0111
39,3,cf_7,,1,,,,,24.3375,,,0.1784,2,True,0.0048,0.0013
40,3,cf_8,1,,,,,,24.3375,,,0.1784,2,False,0.0048,0.0479
41,4,xin,5,4,2,7,1,0,21.2585,3,1.19,,,,,
42,4,cf_1,,,,,,,21.2585,,,0.0,1,False,0.0259,0.0295
43,4,cf_2,,,6,,,,21.2585,,,0.125,2,False,0.0259,0.015
44,4,cf_3,,,3,,,,21.2585,,,0.0313,2,False,0.0259,0.0132
45,4,cf_4,1,,,,,,21.2585,,,0.125,2,False,0.0259,0.0178
46,4,cf_5,,3,,,,,21.2585,,,0.0417,2,False,0.0259,0.0409
47,4,cf_6,3,,,,,,21.2585,,,0.0625,2,True,0.0259,0.0118
48,4,cf_7,,2,,,,,21.2585,,,0.0833,2,True,0.0259,0.0038
49,4,cf_8,4,,,,,,21.2585,,,0.0313,2,True,0.0259,0.007
50,4,cf_9,,,,,,,19.0,,,0.125,1,True,0.0259,0.0009
51,4,cf_10,1,1,,,,,21.2585,,,0.25,3,True,0.0259,0.0024
52,5,xin,2,2,1,2,4,0,27.9904,0,1.22,,,,,
53,5,cf_1,,,,,,,27.9904,,,0.2107,1,False,0.0272,0.0272
54,5,cf_2,,,4,,,,27.9904,,,0.2857,2,False,0.0272,0.0506
55,5,cf_3,,,,,1,,27.9904,,,0.3357,2,False,0.0272,0.019
56,5,cf_4,,,,,3,,27.9904,,,0.2523,2,False,0.0272,0.0139
57,5,cf_5,,,2,,,,27.9904,,,0.2357,2,False,0.0272,0.069
58,5,cf_6,,,6,7,,,27.9904,,,0.4607,3,False,0.0272,0.0632
59,5,cf_7,,,,,2,,27.9904,2,,0.3297,3,True,0.0272,0.0009
60,5,cf_8,,,,7,,,27.9904,7,,0.4607,3,False,0.0272,0.1123
61,5,cf_9,,,,7,1,,27.9904,,,0.4607,3,False,0.0272,0.1124
62,6,xin,2,3,5,4,1,0,27.6817,4,1.06,,,,,
63,6,cf_1,,,,,,,27.3052,,,0.0084,1,True,0.0152,0.0047
64,6,cf_2,,,,,,,25.7867,,,0.0424,1,False,0.0152,0.1086
65,6,cf_3,,,,7,,,27.5811,,,0.1273,2,False,0.0152,0.0084
66,6,cf_4,,,,,,,24.0257,,,0.0819,1,False,0.0152,0.021
67,6,cf_5,,,,,,,23.5141,,,0.0933,1,False,0.0152,0.0489
68,6,cf_6,,,,5,,,26.0814,,,0.0775,2,True,0.0152,0.0027
69,6,cf_7,,,,,,,25.8508,7,,0.166,2,False,0.0152,0.0196
70,6,cf_8,,,,,,,22.5645,,,0.1146,1,False,0.0152,0.0256
71,6,cf_9,1,,,,,,25.5487,,,0.1728,2,False,0.0152,0.0318
72,6,cf_10,,,,,,,22.0992,,,0.125,1,False,0.0152,0.1068
73,7,xin,2,3,6,3,1,0,20.4382,2,1.03,,,,,
74,7,cf_1,,,,,,,20.4284,,,0.0005,1,False,0.2012,0.1487
75,7,cf_2,,,,,,,20.3115,,,0.0065,1,False,0.2012,0.1262
76,7,cf_3,,,,,,,20.221,,,0.0111,1,True,0.2012,0.0505
77,7,cf_4,,,,,,,19.1363,,,0.0663,1,True,0.2012,0.0092
78,7,cf_5,,,,,,,19.0811,,,0.0691,1,True,0.2012,0.0107
79,7,cf_6,,,,,,,19.0,,,0.0733,1,True,0.2012,0.0107
80,7,cf_7,,,,,,,18.9862,,,0.074,1,True,0.2012,0.0102
81,7,cf_8,,,,,,,18.961,,,0.0752,1,True,0.2012,0.0102
82,7,cf_9,,,,,,,17.9842,,,0.125,1,True,0.2012,0.0056
83,7,cf_10,,,,7,,,20.4294,,,0.1254,2,True,0.2012,0.0322
84,8,xin,6,4,1,1,1,0,26.0146,0,1.36,,,,,
85,8,cf_1,2,,,,,,24.8097,,,0.225,2,True,0.1068,0.0033
86,8,cf_2,3,,,5,,,26.0044,,,0.1594,3,False,0.1068,0.0611
87,8,cf_3,1,,,,,,26.0044,3,,0.2511,3,False,0.1068,0.0633
88,8,cf_4,2,,,,,,26.0044,2,,0.1844,3,True,0.1068,0.0342
89,8,cf_5,1,1,,,,,26.0044,,,0.2511,3,True,0.1068,0.0122
90,8,cf_6,2,,,2,,,26.0044,,,0.1219,3,True,0.1068,0.0097
91,8,cf_7,,3,,7,,,25.133,,,0.2581,3,True,0.1068,0.0345
92,8,cf_8,,1,,3,,,24.8558,,,0.2869,3,True,0.1068,0.0007
93,8,cf_9,,2,5,,,,24.8558,,,0.3285,3,True,0.1068,0.0141
94,8,cf_10,1,1,,,,,24.8558,,,0.3702,3,True,0.1068,0.003

### Filtering Valid CFs

In [9]:
from cf_bench.utils import filter_valid_cfs

batch_df = filter_valid_cfs(batch_df)
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,1.33,,,,,
9,0,cf_8,,,,,,,15.9856,5,,0.2143,2,True,0.0743,0.0099
10,0,cf_10,,,,7,,,18.9745,7,,0.2505,3,True,0.0743,0.0051
1,1,xin,3,4,1,2,3,0,22.3757,0,1.24,,,,,
11,1,cf_7,2,,,,1,,22.3757,,,0.2546,3,True,0.0484,0.0105
12,1,cf_8,,2,2,,,,22.3757,7,,0.3796,4,True,0.0484,0.0137
2,2,xin,5,3,1,1,4,0,22.694,7,1.2,,,,,
13,2,cf_2,,,,3,2,,22.68,,,0.1337,3,True,0.0647,0.0185
14,2,cf_7,,,2,,1,,22.6757,,,0.2504,3,True,0.0647,0.0079
15,2,cf_8,,,,3,2,,22.6757,,,0.1338,3,True,0.0647,0.0185
16,2,cf_9,1,2,,,,,22.6757,,,0.2504,3,True,0.0647,0.0031
17,2,cf_10,1,,,,2,,22.6757,,,0.2088,3,True,0.0647,0.0162
3,3,xin,3,3,6,6,2,0,24.3418,1,1.23,,,,,
18,3,cf_2,,,,,,,24.3317,,,0.125,1,True,0.0048,0.0011
19,3,cf_7,,1,,,,,24.3375,,,0.1784,2,True,0.0048,0.0013
4,4,xin,5,4,2,7,1,0,21.2585,3,1.19,,,,,
20,4,cf_6,3,,,,,,21.2585,,,0.0625,2,True,0.0259,0.0118
21,4,cf_7,,2,,,,,21.2585,,,0.0833,2,True,0.0259,0.0038
22,4,cf_8,4,,,,,,21.2585,,,0.0313,2,True,0.0259,0.007
23,4,cf_9,,,,,,,19.0,,,0.125,1,True,0.0259,0.0009
24,4,cf_10,1,1,,,,,21.2585,,,0.25,3,True,0.0259,0.0024
5,5,xin,2,2,1,2,4,0,27.9904,0,1.22,,,,,
25,5,cf_7,,,,,2,,27.9904,2,,0.3297,3,True,0.0272,0.0009
6,6,xin,2,3,5,4,1,0,27.6817,4,1.06,,,,,
26,6,cf_1,,,,,,,27.3052,,,0.0084,1,True,0.0152,0.0047
27,6,cf_6,,,,5,,,26.0814,,,0.0775,2,True,0.0152,0.0027
7,7,xin,2,3,6,3,1,0,20.4382,2,1.03,,,,,
28,7,cf_3,,,,,,,20.221,,,0.0111,1,True,0.2012,0.0505
29,7,cf_4,,,,,,,19.1363,,,0.0663,1,True,0.2012,0.0092
30,7,cf_5,,,,,,,19.0811,,,0.0691,1,True,0.2012,0.0107
31,7,cf_6,,,,,,,19.0,,,0.0733,1,True,0.2012,0.0107
32,7,cf_7,,,,,,,18.9862,,,0.074,1,True,0.2012,0.0102
33,7,cf_8,,,,,,,18.961,,,0.0752,1,True,0.2012,0.0102
34,7,cf_9,,,,,,,17.9842,,,0.125,1,True,0.2012,0.0056
35,7,cf_10,,,,7,,,20.4294,,,0.1254,2,True,0.2012,0.0322
8,8,xin,6,4,1,1,1,0,26.0146,0,1.36,,,,,
36,8,cf_1,2,,,,,,24.8097,,,0.225,2,True,0.1068,0.0033
37,8,cf_4,2,,,,,,26.0044,2,,0.1844,3,True,0.1068,0.0342
38,8,cf_5,1,1,,,,,26.0044,,,0.2511,3,True,0.1068,0.0122
39,8,cf_6,2,,,2,,,26.0044,,,0.1219,3,True,0.1068,0.0097
40,8,cf_7,,3,,7,,,25.133,,,0.2581,3,True,0.1068,0.0345
41,8,cf_8,,1,,3,,,24.8558,,,0.2869,3,True,0.1068,0.0007
42,8,cf_9,,2,5,,,,24.8558,,,0.3285,3,True,0.1068,0.0141
43,8,cf_10,1,1,,,,,24.8558,,,0.3702,3,True,0.1068,0.003

### select one CF

In [10]:
from cf_bench.utils import select_one_cf_per_query

# Select one CF per observation (prefers valid CFs without violations)
single_cf_df = select_one_cf_per_query(batch_df, prefer_no_violations=True)
single_cf_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,1.33,,,,,
9,0,cf_10,,,,7,,,18.9745,7,,0.2505,3,True,0.0743,0.0051
1,1,xin,3,4,1,2,3,0,22.3757,0,1.24,,,,,
10,1,cf_8,,2,2,,,,22.3757,7,,0.3796,4,True,0.0484,0.0137
2,2,xin,5,3,1,1,4,0,22.694,7,1.2,,,,,
11,2,cf_7,,,2,,1,,22.6757,,,0.2504,3,True,0.0647,0.0079
3,3,xin,3,3,6,6,2,0,24.3418,1,1.23,,,,,
12,3,cf_7,,1,,,,,24.3375,,,0.1784,2,True,0.0048,0.0013
4,4,xin,5,4,2,7,1,0,21.2585,3,1.19,,,,,
13,4,cf_7,,2,,,,,21.2585,,,0.0833,2,True,0.0259,0.0038
5,5,xin,2,2,1,2,4,0,27.9904,0,1.22,,,,,
14,5,cf_7,,,,,2,,27.9904,2,,0.3297,3,True,0.0272,0.0009
6,6,xin,2,3,5,4,1,0,27.6817,4,1.06,,,,,
15,6,cf_6,,,,5,,,26.0814,,,0.0775,2,True,0.0152,0.0027
7,7,xin,2,3,6,3,1,0,20.4382,2,1.03,,,,,
16,7,cf_4,,,,,,,19.1363,,,0.0663,1,True,0.2012,0.0092
8,8,xin,6,4,1,1,1,0,26.0146,0,1.36,,,,,
17,8,cf_4,2,,,,,,26.0044,2,,0.1844,3,True,0.1068,0.0342

In [11]:
from cf_bench.dice_adapters import DiceRecommender

recommender = DiceRecommender()

# Format a single query
for idx in range(0, 10):
    print(recommender.format_query(batch_df, query_index=idx))

=== Query index '0' ===
Task / Target: hltprhc
Query instance index: 0

Original instance:
  etfruit: 4
  eatveg: 3
  cgtsmok: 3
  alcfreq: 4
  slprl: 2
  paccnois: 0
  bmi: 18.9866
  dosprt: 0


=== Counterfactuals ===

--- cf_8 ---
Predicted risk: 0.0099
Valid: True
Changes:
  bmi: 18.9866 → 15.9856
  dosprt: 0 → 5

--- cf_10 ---
Predicted risk: 0.0051
Valid: True
Changes:
  alcfreq: 4 → 7
  bmi: 18.9866 → 18.9745
  dosprt: 0 → 7


=== Query index '1' ===
Task / Target: hltprhc
Query instance index: 1

Original instance:
  etfruit: 3
  eatveg: 4
  cgtsmok: 1
  alcfreq: 2
  slprl: 3
  paccnois: 0
  bmi: 22.3757
  dosprt: 0


=== Counterfactuals ===

--- cf_7 ---
Predicted risk: 0.0105
Valid: True
Changes:
  etfruit: 3 → 2
  slprl: 3 → 1

--- cf_8 ---
Predicted risk: 0.0137
Valid: True
Changes:
  eatveg: 4 → 2
  cgtsmok: 1 → 2
  dosprt: 0 → 7


=== Query index '2' ===
Task / Target: hltprhc
Query instance index: 2

Original instance:
  etfruit: 5
  eatveg: 3
  cgtsmok: 1
  alcfreq: 1
  slprl: 4
  paccnois: 0
  bmi: 22.694
  dosprt: 7


=== Counterfactuals ===

--- cf_2 ---
Predicted risk: 0.0185
Valid: True
Changes:
  alcfreq: 1 → 3
  slprl: 4 → 2
  bmi: 22.694 → 22.68

--- cf_7 ---
Predicted risk: 0.0079
Valid: True
Changes:
  cgtsmok: 1 → 2
  slprl: 4 → 1
  bmi: 22.694 → 22.6757

--- cf_8 ---
Predicted risk: 0.0185
Valid: True
Changes:
  alcfreq: 1 → 3
  slprl: 4 → 2
  bmi: 22.694 → 22.6757

--- cf_9 ---
Predicted risk: 0.0031
Valid: True
Changes:
  etfruit: 5 → 1
  eatveg: 3 → 2
  bmi: 22.694 → 22.6757

--- cf_10 ---
Predicted risk: 0.0162
Valid: True
Changes:
  etfruit: 5 → 1
  slprl: 4 → 2
  bmi: 22.694 → 22.6757


=== Query index '3' ===
Task / Target: hltprhc
Query instance index: 3

Original instance:
  etfruit: 3
  eatveg: 3
  cgtsmok: 6
  alcfreq: 6
  slprl: 2
  paccnois: 0
  bmi: 24.3418
  dosprt: 1


=== Counterfactuals ===

--- cf_2 ---
Predicted risk: 0.0011
Valid: True
Changes:
  bmi: 24.3418 → 24.3317

--- cf_7 ---
Predicted risk: 0.0013
Valid: True
Changes:
  eatveg: 3 → 1
  bmi: 24.3418 → 24.3375


=== Query index '4' ===
Task / Target: hltprhc
Query instance index: 4

Original instance:
  etfruit: 5
  eatveg: 4
  cgtsmok: 2
  alcfreq: 7
  slprl: 1
  paccnois: 0
  bmi: 21.2585
  dosprt: 3


=== Counterfactuals ===

--- cf_6 ---
Predicted risk: 0.0118
Valid: True
Changes:
  etfruit: 5 → 3

--- cf_7 ---
Predicted risk: 0.0038
Valid: True
Changes:
  eatveg: 4 → 2

--- cf_8 ---
Predicted risk: 0.007
Valid: True
Changes:
  etfruit: 5 → 4

--- cf_9 ---
Predicted risk: 0.0009
Valid: True
Changes:
  bmi: 21.2585 → 19.0

--- cf_10 ---
Predicted risk: 0.0024
Valid: True
Changes:
  etfruit: 5 → 1
  eatveg: 4 → 1


=== Query index '5' ===
Task / Target: hltprhc
Query instance index: 5

Original instance:
  etfruit: 2
  eatveg: 2
  cgtsmok: 1
  alcfreq: 2
  slprl: 4
  paccnois: 0
  bmi: 27.9904
  dosprt: 0


=== Counterfactuals ===

--- cf_7 ---
Predicted risk: 0.0009
Valid: True
Changes:
  slprl: 4 → 2
  dosprt: 0 → 2


=== Query index '6' ===
Task / Target: hltprhc
Query instance index: 6

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 5
  alcfreq: 4
  slprl: 1
  paccnois: 0
  bmi: 27.6817
  dosprt: 4


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.0047
Valid: True
Changes:
  bmi: 27.6817 → 27.3052

--- cf_6 ---
Predicted risk: 0.0027
Valid: True
Changes:
  alcfreq: 4 → 5
  bmi: 27.6817 → 26.0814


=== Query index '7' ===
Task / Target: hltprhc
Query instance index: 7

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 6
  alcfreq: 3
  slprl: 1
  paccnois: 0
  bmi: 20.4382
  dosprt: 2


=== Counterfactuals ===

--- cf_3 ---
Predicted risk: 0.0505
Valid: True
Changes:
  bmi: 20.4382 → 20.221

--- cf_4 ---
Predicted risk: 0.0092
Valid: True
Changes:
  bmi: 20.4382 → 19.1363

--- cf_5 ---
Predicted risk: 0.0107
Valid: True
Changes:
  bmi: 20.4382 → 19.0811

--- cf_6 ---
Predicted risk: 0.0107
Valid: True
Changes:
  bmi: 20.4382 → 19.0

--- cf_7 ---
Predicted risk: 0.0102
Valid: True
Changes:
  bmi: 20.4382 → 18.9862

--- cf_8 ---
Predicted risk: 0.0102
Valid: True
Changes:
  bmi: 20.4382 → 18.961

--- cf_9 ---
Predicted risk: 0.0056
Valid: True
Changes:
  bmi: 20.4382 → 17.9842

--- cf_10 ---
Predicted risk: 0.0322
Valid: True
Changes:
  alcfreq: 3 → 7
  bmi: 20.4382 → 20.4294


=== Query index '8' ===
Task / Target: hltprhc
Query instance index: 8

Original instance:
  etfruit: 6
  eatveg: 4
  cgtsmok: 1
  alcfreq: 1
  slprl: 1
  paccnois: 0
  bmi: 26.0146
  dosprt: 0


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.0033
Valid: True
Changes:
  etfruit: 6 → 2
  bmi: 26.0146 → 24.8097

--- cf_4 ---
Predicted risk: 0.0342
Valid: True
Changes:
  etfruit: 6 → 2
  bmi: 26.0146 → 26.0044
  dosprt: 0 → 2

--- cf_5 ---
Predicted risk: 0.0122
Valid: True
Changes:
  etfruit: 6 → 1
  eatveg: 4 → 1
  bmi: 26.0146 → 26.0044

--- cf_6 ---
Predicted risk: 0.0097
Valid: True
Changes:
  etfruit: 6 → 2
  alcfreq: 1 → 2
  bmi: 26.0146 → 26.0044

--- cf_7 ---
Predicted risk: 0.0345
Valid: True
Changes:
  eatveg: 4 → 3
  alcfreq: 1 → 7
  bmi: 26.0146 → 25.133

--- cf_8 ---
Predicted risk: 0.0007
Valid: True
Changes:
  eatveg: 4 → 1
  alcfreq: 1 → 3
  bmi: 26.0146 → 24.8558

--- cf_9 ---
Predicted risk: 0.0141
Valid: True
Changes:
  eatveg: 4 → 2
  cgtsmok: 1 → 5
  bmi: 26.0146 → 24.8558

--- cf_10 ---
Predicted risk: 0.003
Valid: True
Changes:
  etfruit: 6 → 1
  eatveg: 4 → 1
  bmi: 26.0146 → 24.8558


=== Query index '9' ===
No recommendations available.