### imports and pandas settings

In [1]:
import os
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv

In [2]:
pd.set_option("display.max_rows", None)

### set the path to data file

In [3]:
load_dotenv()

CF_OUTPUTS = Path(os.getenv("CF_OUTPUTS"))
print(CF_OUTPUTS)
print(CF_OUTPUTS.is_dir())

/home/dyretna/Dokument/Code/GitHub/nightingale_projects/cf_bench/cf_outputs
True

In [4]:
batch_data = CF_OUTPUTS / "SMOTE" / "base_rf_SMOTE_midthres_2026-05-06" / "annotated.csv"

### load data 
convert to string to fillna with whitespace
we drop:  
- target_risk (half of "risk_before") , and 
- "hltprhc"

we rename "original" in df_id to "xin" (HL standards)

In [5]:
# Load CSV
batch_df = pd.read_csv(batch_data)

In [6]:
# Feature columns
feature_cols = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "bmi", "dosprt"]

# dtypes
int_columns = ["etfruit", "eatveg", "cgtsmok", "alcfreq", "slprl", "paccnois", "dosprt", "hltprhc", "Nchanged"]
float_columns = ["bmi", "gower_distance", "risk_before", "predicted_risk_after", "cf_gen_time_sec"]


# Convert and fill NaN with empty strings
batch_df[int_columns] = batch_df[int_columns].astype("Int64").astype("string").fillna("")
batch_df[float_columns] = batch_df[float_columns].round(4).astype("string").fillna("")
batch_df["valid"] = batch_df["valid"].astype("string").fillna("")

In [7]:
batch_df = batch_df.drop(columns=["hltprhc", "target_risk"])
batch_df["cf_id"] = batch_df["cf_id"].replace({"original": "xin"})

### All CFs

In [8]:
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,2.89,,,,,
1,0,cf_1,,,,,,,17.4055,,,0.9484,1,False,0.1667,0.1567
2,0,cf_2,,,,7,,,18.9745,,,0.8756,2,False,0.1667,0.27
3,0,cf_3,3,,,,,,18.9386,,,0.8772,2,False,0.1667,0.1967
4,0,cf_4,,,,,,,18.0396,5,,0.919,2,False,0.1667,0.1933
5,0,cf_5,,,6,,,,17.6478,,,0.9371,2,False,0.1667,0.14
6,0,cf_6,,,,7,,,16.6455,,,0.9837,2,False,0.1667,0.3
7,0,cf_7,,,,6,,,16.2935,,,1.0,2,False,0.1667,0.36
8,0,cf_8,,,6,7,,,18.9745,,,0.8756,3,False,0.1667,0.1833
9,0,cf_9,,,,7,,,18.9745,7,,0.8756,3,True,0.1667,0.0567
10,0,cf_10,1,,,,,,18.9619,2,,0.8761,3,False,0.1667,0.1233
11,1,xin,3,4,1,2,3,0,22.3757,0,62.56,,,,,
12,1,cf_1,,,4,,,,22.3757,4,,0.8796,3,True,0.52,0.1967
13,1,cf_2,,,,3,1,,22.3757,,,0.8796,3,True,0.52,0.02
14,1,cf_3,,,,,2,,22.3757,7,,0.8796,3,False,0.52,0.3267
15,1,cf_4,,,,,1,,22.3757,1,,0.8796,3,True,0.52,0.1233
16,1,cf_5,2,,,,1,,22.3757,,,0.8796,3,True,0.52,0.0367
17,1,cf_6,,,,7,,,22.3757,7,,0.8796,3,True,0.52,0.1867
18,1,cf_7,,3,6,6,,,22.3757,,,0.8796,4,False,0.52,0.3267
19,1,cf_8,,1,,7,,,22.3757,7,,0.8796,4,True,0.52,0.23
20,1,cf_9,1,2,,,,,22.3757,2,,0.8796,4,True,0.52,0.0867
21,2,xin,5,3,1,1,4,0,22.694,7,3.04,,,,,
22,2,cf_1,,,,3,,,20.0,,,0.923,2,False,0.3333,0.3767
23,2,cf_2,,1,,5,,,22.68,,,0.8753,3,False,0.3333,0.2767
24,2,cf_3,3,,,,2,,22.68,,,0.8753,3,True,0.3333,0.0633
25,2,cf_4,,,,4,2,,22.6757,,,0.8753,3,False,0.3333,0.33
26,2,cf_5,,,,3,2,,22.6757,,,0.8753,3,False,0.3333,0.42
27,2,cf_6,,,,6,1,,22.6757,,,0.8753,3,False,0.3333,0.2633
28,2,cf_7,,,,,,,15.6787,,,1.0,1,False,0.3333,0.31
29,2,cf_8,1,,,3,,,20.0,,,0.923,3,False,0.3333,0.17
30,2,cf_9,,,2,6,1,,22.68,,,0.8753,4,True,0.3333,0.07
31,2,cf_10,2,,,5,1,,22.68,,,0.8753,4,False,0.3333,0.31
32,3,xin,3,3,6,6,2,0,24.3418,1,3.29,,,,,
33,3,cf_1,,,,,,,24.3375,,,0.8753,1,False,0.0367,0.0333
34,3,cf_2,,,,,,,22.2995,,,1.0,1,False,0.0367,0.3167
35,3,cf_3,,,,7,,,24.3375,,,0.8753,2,False,0.0367,0.0467
36,3,cf_4,,,,,,,24.3375,3,,0.8753,2,False,0.0367,0.0233
37,3,cf_5,,,,,1,,24.3375,,,0.8753,2,False,0.0367,0.42
38,3,cf_6,,,,,,,24.3375,4,,0.8753,2,False,0.0367,0.0967
39,3,cf_7,,,,,1,,22.9,,,0.9632,2,False,0.0367,0.2033
40,3,cf_8,1,,,,,,24.3375,2,,0.8753,3,False,0.0367,0.36
41,3,cf_9,1,,,,,,24.3375,3,,0.8753,3,False,0.0367,0.25
42,3,cf_10,1,,,,,,24.3375,6,,0.8753,3,False,0.0367,0.2867
43,4,xin,5,4,2,7,1,0,21.2585,3,3.39,,,,,
44,4,cf_1,,,,,,,21.2585,,,0.9868,1,False,0.0067,0.0067
45,4,cf_2,,,6,,,,21.2585,,,0.9868,2,True,0.0067,0.0
46,4,cf_3,3,,,,,,21.2585,,,0.9868,2,False,0.0067,0.1033
47,4,cf_4,1,,,,,,21.2585,,,0.9868,2,False,0.0067,0.2567
48,4,cf_5,4,,,,,,21.2585,,,0.9868,2,False,0.0067,0.01
49,4,cf_6,,3,,,,,21.2585,,,0.9868,2,False,0.0067,0.02
50,4,cf_7,,,5,,,,21.2585,,,0.9868,2,False,0.0067,0.02
51,4,cf_8,,,3,,,,21.2585,,,0.9868,2,False,0.0067,0.0067
52,4,cf_9,4,,,,,,21.2585,5,,0.9868,3,False,0.0067,0.0367
53,4,cf_10,1,1,,,,,21.2585,,,0.9868,3,False,0.0067,0.2067
54,5,xin,2,2,1,2,4,0,27.9904,0,3.2,,,,,
55,5,cf_1,,,2,,,,27.9904,,,1.0857,2,False,0.52,0.49
56,5,cf_2,,,,7,,,27.9904,,,1.0857,2,False,0.52,0.3833
57,5,cf_3,,,4,,,,27.9904,7,,1.0857,3,False,0.52,0.4567
58,5,cf_4,,1,,,,,27.9904,6,,1.0857,3,True,0.52,0.2233
59,5,cf_5,,,,,2,,27.9904,2,,1.0857,3,False,0.52,0.4233
60,5,cf_6,,,,4,1,,27.9904,,,1.0857,3,False,0.52,0.3533
61,5,cf_7,,,,5,1,,27.9904,,,1.0857,3,False,0.52,0.27
62,5,cf_8,,,,6,1,,27.9904,,,1.0857,3,False,0.52,0.4967
63,5,cf_9,,,4,,1,,27.9904,,,1.0857,3,False,0.52,0.3033
64,5,cf_10,,,,7,1,,27.9904,,,1.0857,3,True,0.52,0.2333
65,6,xin,2,3,5,4,1,0,27.6817,4,2.83,,,,,
66,6,cf_1,,,,,,,26.9185,,,0.9018,1,False,0.4233,0.2533
67,6,cf_2,,,,,,,26.893,,,0.9027,1,False,0.4233,0.25
68,6,cf_3,,,,,,,26.572,,,0.914,1,True,0.4233,0.1767
69,6,cf_4,,,,,,,25.7732,,,0.9421,1,True,0.4233,0.17
70,6,cf_5,,,,,,,25.6794,,,0.9454,1,True,0.4233,0.1533
71,6,cf_6,,,,,,,24.7571,,,0.9778,1,True,0.4233,0.1767
72,6,cf_7,,,,,,,24.5466,,,0.9852,1,False,0.4233,0.37
73,6,cf_8,,,,,,,24.3746,,,0.9913,1,False,0.4233,0.29
74,6,cf_9,,,,,,,27.2924,5,,0.8887,2,False,0.4233,0.4467
75,6,cf_10,,,,,,,24.1268,,,1.0,1,True,0.4233,0.17
76,7,xin,2,3,6,3,1,0,20.4382,2,2.85,,,,,
77,7,cf_1,,,,,,,20.4284,,,0.8754,1,False,0.1067,0.11
78,7,cf_2,,,,,,,19.5533,,,0.9146,1,False,0.1067,0.0867
79,7,cf_3,,,,,,,19.3817,,,0.9222,1,False,0.1067,0.09
80,7,cf_4,,,,,,,19.1273,,,0.9336,1,False,0.1067,0.1067
81,7,cf_5,,,,,,,18.7864,,,0.9489,1,False,0.1067,0.0767
82,7,cf_6,,,,,,,17.6428,,,1.0,1,False,0.1067,0.0733
83,7,cf_7,,,,7,,,20.4294,,,0.8754,2,True,0.1067,0.0367
84,7,cf_8,,,,6,,,20.4284,,,0.8754,2,False,0.1067,0.0833
85,7,cf_9,,,,4,,,20.4284,,,0.8754,2,False,0.1067,0.32
86,7,cf_10,,,,,,,20.4284,5,,0.8754,2,False,0.1067,0.1633
87,8,xin,6,4,1,1,1,0,26.0146,0,3.54,,,,,
88,8,cf_1,,1,,,,,25.1082,,,0.8946,2,False,0.2267,0.16
89,8,cf_2,3,,,,,,26.0086,7,,0.8751,3,False,0.2267,0.18
90,8,cf_3,,,6,7,,,26.0044,,,0.8752,3,False,0.2267,0.2333
91,8,cf_4,,1,,4,,,26.0044,,,0.8752,3,True,0.2267,0.0433
92,8,cf_5,,1,,,,,26.0044,4,,0.8752,3,False,0.2267,0.1367
93,8,cf_6,1,,,,,,26.0044,6,,0.8752,3,False,0.2267,0.1333
94,8,cf_7,1,1,,,,,25.1082,,,0.8946,3,True,0.2267,0.0967
95,8,cf_8,5,,,4,,,25.1082,,,0.8946,3,True,0.2267,0.07
96,8,cf_9,,,,7,,,20.2246,,,1.0,2,False,0.2267,0.28
97,8,cf_10,1,2,,,,,26.0044,6,,0.8752,4,False,0.2267,0.3067

### Filtering Valid CFs

In [9]:
from cf_bench.utils import filter_valid_cfs

batch_df = filter_valid_cfs(batch_df)
batch_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,2.89,,,,,
9,0,cf_9,,,,7,,,18.9745,7,,0.8756,3,True,0.1667,0.0567
1,1,xin,3,4,1,2,3,0,22.3757,0,62.56,,,,,
10,1,cf_1,,,4,,,,22.3757,4,,0.8796,3,True,0.52,0.1967
11,1,cf_2,,,,3,1,,22.3757,,,0.8796,3,True,0.52,0.02
12,1,cf_4,,,,,1,,22.3757,1,,0.8796,3,True,0.52,0.1233
13,1,cf_5,2,,,,1,,22.3757,,,0.8796,3,True,0.52,0.0367
14,1,cf_6,,,,7,,,22.3757,7,,0.8796,3,True,0.52,0.1867
15,1,cf_8,,1,,7,,,22.3757,7,,0.8796,4,True,0.52,0.23
16,1,cf_9,1,2,,,,,22.3757,2,,0.8796,4,True,0.52,0.0867
2,2,xin,5,3,1,1,4,0,22.694,7,3.04,,,,,
17,2,cf_3,3,,,,2,,22.68,,,0.8753,3,True,0.3333,0.0633
18,2,cf_9,,,2,6,1,,22.68,,,0.8753,4,True,0.3333,0.07
3,3,xin,3,3,6,6,2,0,24.3418,1,3.29,,,,,
31,3,,,,,,,,,,,,,False,,
4,4,xin,5,4,2,7,1,0,21.2585,3,3.39,,,,,
19,4,cf_2,,,6,,,,21.2585,,,0.9868,2,True,0.0067,0.0
5,5,xin,2,2,1,2,4,0,27.9904,0,3.2,,,,,
20,5,cf_4,,1,,,,,27.9904,6,,1.0857,3,True,0.52,0.2233
21,5,cf_10,,,,7,1,,27.9904,,,1.0857,3,True,0.52,0.2333
6,6,xin,2,3,5,4,1,0,27.6817,4,2.83,,,,,
22,6,cf_3,,,,,,,26.572,,,0.914,1,True,0.4233,0.1767
23,6,cf_4,,,,,,,25.7732,,,0.9421,1,True,0.4233,0.17
24,6,cf_5,,,,,,,25.6794,,,0.9454,1,True,0.4233,0.1533
25,6,cf_6,,,,,,,24.7571,,,0.9778,1,True,0.4233,0.1767
26,6,cf_10,,,,,,,24.1268,,,1.0,1,True,0.4233,0.17
7,7,xin,2,3,6,3,1,0,20.4382,2,2.85,,,,,
27,7,cf_7,,,,7,,,20.4294,,,0.8754,2,True,0.1067,0.0367
8,8,xin,6,4,1,1,1,0,26.0146,0,3.54,,,,,
28,8,cf_4,,1,,4,,,26.0044,,,0.8752,3,True,0.2267,0.0433
29,8,cf_7,1,1,,,,,25.1082,,,0.8946,3,True,0.2267,0.0967
30,8,cf_8,5,,,4,,,25.1082,,,0.8946,3,True,0.2267,0.07

### select one CF

In [10]:
from cf_bench.utils import select_one_cf_per_query

# Select one CF per observation (prefers valid CFs without violations)
single_cf_df = select_one_cf_per_query(batch_df, prefer_no_violations=True)
single_cf_df

,query_index,cf_id,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,cf_gen_time_sec,gower_distance,Nchanged,valid,risk_before,predicted_risk_after
0,0,xin,4,3,3,4,2,0,18.9866,0,2.89,,,,,
9,0,cf_9,,,,7,,,18.9745,7,,0.8756,3,True,0.1667,0.0567
1,1,xin,3,4,1,2,3,0,22.3757,0,62.56,,,,,
10,1,cf_1,,,4,,,,22.3757,4,,0.8796,3,True,0.52,0.1967
2,2,xin,5,3,1,1,4,0,22.694,7,3.04,,,,,
11,2,cf_9,,,2,6,1,,22.68,,,0.8753,4,True,0.3333,0.07
3,3,xin,3,3,6,6,2,0,24.3418,1,3.29,,,,,
12,3,,,,,,,,,,,,,False,,
4,4,xin,5,4,2,7,1,0,21.2585,3,3.39,,,,,
13,4,cf_2,,,6,,,,21.2585,,,0.9868,2,True,0.0067,0.0
5,5,xin,2,2,1,2,4,0,27.9904,0,3.2,,,,,
14,5,cf_10,,,,7,1,,27.9904,,,1.0857,3,True,0.52,0.2333
6,6,xin,2,3,5,4,1,0,27.6817,4,2.83,,,,,
15,6,cf_4,,,,,,,25.7732,,,0.9421,1,True,0.4233,0.17
7,7,xin,2,3,6,3,1,0,20.4382,2,2.85,,,,,
16,7,cf_7,,,,7,,,20.4294,,,0.8754,2,True,0.1067,0.0367
8,8,xin,6,4,1,1,1,0,26.0146,0,3.54,,,,,
17,8,cf_4,,1,,4,,,26.0044,,,0.8752,3,True,0.2267,0.0433

In [11]:
from cf_bench.dice_adapters import DiceRecommender

recommender = DiceRecommender()

# Format a single query
for idx in range(0, 10):
    print(recommender.format_query(batch_df, query_index=idx))

=== Query index '0' ===
Task / Target: hltprhc
Query instance index: 0

Original instance:
  etfruit: 4
  eatveg: 3
  cgtsmok: 3
  alcfreq: 4
  slprl: 2
  paccnois: 0
  bmi: 18.9866
  dosprt: 0


=== Counterfactuals ===

--- cf_9 ---
Predicted risk: 0.0567
Valid: True
Changes:
  alcfreq: 4 → 7
  bmi: 18.9866 → 18.9745
  dosprt: 0 → 7


=== Query index '1' ===
Task / Target: hltprhc
Query instance index: 1

Original instance:
  etfruit: 3
  eatveg: 4
  cgtsmok: 1
  alcfreq: 2
  slprl: 3
  paccnois: 0
  bmi: 22.3757
  dosprt: 0


=== Counterfactuals ===

--- cf_1 ---
Predicted risk: 0.1967
Valid: True
Changes:
  cgtsmok: 1 → 4
  dosprt: 0 → 4

--- cf_2 ---
Predicted risk: 0.02
Valid: True
Changes:
  alcfreq: 2 → 3
  slprl: 3 → 1

--- cf_4 ---
Predicted risk: 0.1233
Valid: True
Changes:
  slprl: 3 → 1
  dosprt: 0 → 1

--- cf_5 ---
Predicted risk: 0.0367
Valid: True
Changes:
  etfruit: 3 → 2
  slprl: 3 → 1

--- cf_6 ---
Predicted risk: 0.1867
Valid: True
Changes:
  alcfreq: 2 → 7
  dosprt: 0 → 7

--- cf_8 ---
Predicted risk: 0.23
Valid: True
Changes:
  eatveg: 4 → 1
  alcfreq: 2 → 7
  dosprt: 0 → 7

--- cf_9 ---
Predicted risk: 0.0867
Valid: True
Changes:
  etfruit: 3 → 1
  eatveg: 4 → 2
  dosprt: 0 → 2


=== Query index '2' ===
Task / Target: hltprhc
Query instance index: 2

Original instance:
  etfruit: 5
  eatveg: 3
  cgtsmok: 1
  alcfreq: 1
  slprl: 4
  paccnois: 0
  bmi: 22.694
  dosprt: 7


=== Counterfactuals ===

--- cf_3 ---
Predicted risk: 0.0633
Valid: True
Changes:
  etfruit: 5 → 3
  slprl: 4 → 2
  bmi: 22.694 → 22.68

--- cf_9 ---
Predicted risk: 0.07
Valid: True
Changes:
  cgtsmok: 1 → 2
  alcfreq: 1 → 6
  slprl: 4 → 1
  bmi: 22.694 → 22.68


=== Query index '3' ===
Task / Target: hltprhc
Query instance index: 3

Original instance:
  etfruit: 3
  eatveg: 3
  cgtsmok: 6
  alcfreq: 6
  slprl: 2
  paccnois: 0
  bmi: 24.3418
  dosprt: 1


=== Counterfactuals ===

---  ---
Valid: False
No feature changes.


=== Query index '4' ===
Task / Target: hltprhc
Query instance index: 4

Original instance:
  etfruit: 5
  eatveg: 4
  cgtsmok: 2
  alcfreq: 7
  slprl: 1
  paccnois: 0
  bmi: 21.2585
  dosprt: 3


=== Counterfactuals ===

--- cf_2 ---
Predicted risk: 0.0
Valid: True
Changes:
  cgtsmok: 2 → 6


=== Query index '5' ===
Task / Target: hltprhc
Query instance index: 5

Original instance:
  etfruit: 2
  eatveg: 2
  cgtsmok: 1
  alcfreq: 2
  slprl: 4
  paccnois: 0
  bmi: 27.9904
  dosprt: 0


=== Counterfactuals ===

--- cf_4 ---
Predicted risk: 0.2233
Valid: True
Changes:
  eatveg: 2 → 1
  dosprt: 0 → 6

--- cf_10 ---
Predicted risk: 0.2333
Valid: True
Changes:
  alcfreq: 2 → 7
  slprl: 4 → 1


=== Query index '6' ===
Task / Target: hltprhc
Query instance index: 6

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 5
  alcfreq: 4
  slprl: 1
  paccnois: 0
  bmi: 27.6817
  dosprt: 4


=== Counterfactuals ===

--- cf_3 ---
Predicted risk: 0.1767
Valid: True
Changes:
  bmi: 27.6817 → 26.572

--- cf_4 ---
Predicted risk: 0.17
Valid: True
Changes:
  bmi: 27.6817 → 25.7732

--- cf_5 ---
Predicted risk: 0.1533
Valid: True
Changes:
  bmi: 27.6817 → 25.6794

--- cf_6 ---
Predicted risk: 0.1767
Valid: True
Changes:
  bmi: 27.6817 → 24.7571

--- cf_10 ---
Predicted risk: 0.17
Valid: True
Changes:
  bmi: 27.6817 → 24.1268


=== Query index '7' ===
Task / Target: hltprhc
Query instance index: 7

Original instance:
  etfruit: 2
  eatveg: 3
  cgtsmok: 6
  alcfreq: 3
  slprl: 1
  paccnois: 0
  bmi: 20.4382
  dosprt: 2


=== Counterfactuals ===

--- cf_7 ---
Predicted risk: 0.0367
Valid: True
Changes:
  alcfreq: 3 → 7
  bmi: 20.4382 → 20.4294


=== Query index '8' ===
Task / Target: hltprhc
Query instance index: 8

Original instance:
  etfruit: 6
  eatveg: 4
  cgtsmok: 1
  alcfreq: 1
  slprl: 1
  paccnois: 0
  bmi: 26.0146
  dosprt: 0


=== Counterfactuals ===

--- cf_4 ---
Predicted risk: 0.0433
Valid: True
Changes:
  eatveg: 4 → 1
  alcfreq: 1 → 4
  bmi: 26.0146 → 26.0044

--- cf_7 ---
Predicted risk: 0.0967
Valid: True
Changes:
  etfruit: 6 → 1
  eatveg: 4 → 1
  bmi: 26.0146 → 25.1082

--- cf_8 ---
Predicted risk: 0.07
Valid: True
Changes:
  etfruit: 6 → 5
  alcfreq: 1 → 4
  bmi: 26.0146 → 25.1082


=== Query index '9' ===
No recommendations available.