In [49]:
from aiwhatif_cf.config import DATA_DIR, MODELS_DIR

TRAINING_PATH = DATA_DIR / "eta.csv"
TRAINING_PATH.is_file()

TEST_PATH = DATA_DIR / "ete.csv"
TEST_PATH.is_file()

True

In [50]:
import pandas as pd

hl_df_train = pd.read_csv(TRAINING_PATH, index_col=0)
hl_df_test = pd.read_csv(TEST_PATH, index_col=0)

hl_df_full = pd.concat([hl_df_train, hl_df_test], axis=0)

In [51]:
hl_df_train.head()

,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,hltprhc
36122,3,3,6,5,1,0,21.453287,2,0
24898,6,3,2,2,4,0,25.181077,7,0
14759,4,1,3,2,2,0,23.529412,5,0
8874,5,4,4,2,3,0,30.487805,2,0
39895,4,4,2,2,2,0,26.769780,2,0

In [52]:
hl_df_full

,etfruit,eatveg,cgtsmok,alcfreq,slprl,paccnois,bmi,dosprt,hltprhc
36122,3,3,6,5,1,0,21.453287,2,0
24898,6,3,2,2,4,0,25.181077,7,0
14759,4,1,3,2,2,0,23.529412,5,0
8874,5,4,4,2,3,0,30.487805,2,0
39895,4,4,2,2,2,0,26.769780,2,0
...,...,...,...,...,...,...,...,...,...
41077,3,3,2,3,1,0,23.547881,5,0
41082,4,5,4,6,2,0,34.312524,0,0
41084,2,3,6,7,2,0,28.303850,5,0
41085,2,3,3,5,3,0,27.161612,2,0
41101,3,3,6,5,3,0,21.477087,3,1

In [53]:
hl_df_full.info()

<class 'pandas.core.frame.DataFrame'>
Index: 41104 entries, 36122 to 41101
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   etfruit   41104 non-null  int64
 1   eatveg    41104 non-null  int64
 2   cgtsmok   41104 non-null  int64
 3   alcfreq   41104 non-null  int64
 4   slprl     41104 non-null  int64
 5   paccnois  41104 non-null  int64
 6   bmi       41104 non-null  float64
 7   dosprt    41104 non-null  int64
 8   hltprhc   41104 non-null  int64
dtypes: float64(1), int64(8)
memory usage: 3.1 MB

In [54]:
continous_cols = ["bmi"]
int_cols = [col for col in list(hl_df_full.columns)
            if col not in continous_cols]

In [55]:
uniques = {}

for col in int_cols:
    uniques[col] = sorted(hl_df_full[col].unique())

for k, v in uniques.items():
    print(f"{k:8} : {v}")

etfruit  : [1, 2, 3, 4, 5, 6, 7]
eatveg   : [1, 2, 3, 4, 5, 6, 7]
cgtsmok  : [1, 2, 3, 4, 5, 6]
alcfreq  : [1, 2, 3, 4, 5, 6, 7]
slprl    : [1, 2, 3, 4]
paccnois : [0, 1]
dosprt   : [0, 1, 2, 3, 4, 5, 6, 7]
hltprhc  : [0, 1]

In [56]:
hl_df_full.to_csv(DATA_DIR / "full.csv")